### ISSUE TITLE
i18n(add English description and Readme)

### ISSUE THREAD

**Issue by wey-gu** [nebula-contrib/ngbatis#1]
Thanks a lot, @CorvusYe , this is extra awesome!!!!!!

We may need English readme and documentation, just mark as an issue here, I or other guys could help to translate.

You are amazing!!!

**Comment by CorvusYe** [comment]
Thanks for your advice. @wey-gu 
I am still unfamiliar with the cooperation on GitHub.
Therefore, the branch that can PR has not been opened for a long time. 
Now the [branch](https://github.com/CorvusYe/ngbatis/tree/1-i18nadd-english-description-and-readme) is opened for commit.
Thanks again.

**Comment by wey-gu** [comment]
Will do that later @CorvusYe :), thanks!

BTW, we are working on the donation to migrate this to nebula-contrib org, it's still WIP, sorry for the long wait :)

**Comment by CorvusYe** [comment]
https://corvusye.github.io/ngbatis-docs/#/
