### ISSUE TITLE
discuss: about vertex/edge convertint to Map when java entity type is absent.

### ISSUE THREAD

**Issue by CorvusYe** [nebula-contrib/ngbatis#103]
RFC: https://github.com/CorvusYe/ngbatis/commit/b8e71f7f55f891dbf710a524b24100a23f0554c8

@hejiahuichengxuyuan @wey-gu

For example: there are no PersonDao extended NebulaDaoBasic<Person, Serializable>
```cql
        GET SUBGRAPH WITH PROP 3 STEPS FROM "叶小南"
        BOTH like
        YIELD VERTICES AS nodes, EDGES AS relationships
```
the below result will be returned.

[more info ...](https://github.com/CorvusYe/ngbatis/commit/4b21386e496d591614d768236f2b5bc27f16cdc2)

![image](https://user-images.githubusercontent.com/15630211/205581332-cf3c7f3c-dc20-4153-a4dd-e21391c87248.png)

**Comment by hejiahuichengxuyuan** [comment]
希望有一个类而不是map，  现在我做 Vertex 的是这样的，但是 label和nodeShowPic 是额外属性

```
public class VertexReturnVO {

    /**
     * key
     */
    @ApiModelProperty("id")
    private String id;

    @ApiModelProperty("显示该点所拥有的tag(tag独有)")
    private List<TagsVO> tags;

    @ApiModelProperty("显示该数据是点还是边,vertex或edge")
    private String type;

    /**
     * 数据
     */
    @ApiModelProperty("数据")
    private Map<String, Map<String, Object>> properties;

    /**
     * 显示的label
     */
    @ApiModelProperty("显示的label")
    private String label;

    /**
     * 显示的图片(Tag独有)
     */
    @ApiModelProperty("显示的图片(Tag独有)")
    private String nodeShowPic;

}
```

**Comment by CorvusYe** [comment]
嗯嗯，那由ngbatis定义一个统一的 POJO，再新增一个针对 POJO 的 EdgeAndNodeResultHandler 应该就能满足需求

**Comment by CorvusYe** [comment]
> ![image](https://user-images.githubusercontent.com/15630211/205581332-cf3c7f3c-dc20-4153-a4dd-e21391c87248.png)

这个结果应该是满足 null 的那条需求吧。

**Comment by hejiahuichengxuyuan** [comment]
嗯嗯这样好多了
