### ISSUE TITLE
Collection<?>结果集处理时无法识别泛型

### ISSUE THREAD

**Issue by zb139407** [nebula-contrib/ngbatis#107]
<img width="964" alt="微信图片_20221211215421" src="https://user-images.githubusercontent.com/62243886/206907903-dafd2fac-a7a3-4751-b17c-82acdbe431d6.png">
一开始用List接收结果集，可以识别List，无法识别泛型
<img width="964" alt="微信图片_20221211215245" src="https://user-images.githubusercontent.com/62243886/206907965-e1969417-6e64-4601-9f1f-ebfa88264986.png">
换Collection同样无法识别

**Comment by CorvusYe** [comment]
xml 是怎么定义的？

**Comment by CorvusYe** [comment]
方便在 AbstractResultHandler 45 行断点看下吗，启动的时候，那边是注册类型处理的地方

**Comment by zb139407** [comment]
是忘记加resultType了

**Comment by CorvusYe** [comment]
嗯嗯，Collection 类型的我自己有时候也忘，哈哈哈
