### ISSUE TITLE
Consider defining a bean of type 'com.*.mapper.TagMapper' in your configuration.

### ISSUE THREAD

**Issue by ZhangJinzhaoGit** [nebula-contrib/ngbatis#111]
你好，麻烦问一下，我的项目启动不起来，报这个错误，
![image](https://user-images.githubusercontent.com/41096054/208622568-3ac24bd9-528f-4fbc-b332-a9be8469a420.png)
![image](https://user-images.githubusercontent.com/41096054/208622689-9bad802a-55dd-4f8e-b19d-80151c345c64.png)
![image](https://user-images.githubusercontent.com/41096054/208622900-ac572921-8bf3-4e90-86d2-8b810febbb89.png)

麻烦帮忙看看，谢谢

**Comment by CorvusYe** [comment]
可以看下xml开头，xml里面的namespace需要写完整包名，不支持通配符*

**Comment by ZhangJinzhaoGit** [comment]
![image](https://user-images.githubusercontent.com/41096054/208660001-d9c4cd9d-52ee-4f93-a823-f0fe93343365.png)
我是这么写的
![image](https://user-images.githubusercontent.com/41096054/208660163-a2b00421-84a8-4d10-97e8-c580e1296820.png)

**Comment by CorvusYe** [comment]
这么写没问题啊，有没有其他文件

**Comment by ZhangJinzhaoGit** [comment]
没有，只有这一个mapper，我用master分支里面demo把数据库地址换成我的启动也是报这个，和spring版本有关系吗？
![image](https://user-images.githubusercontent.com/41096054/208667246-a3884aea-73f2-4d7b-b8bc-39ec513a8347.png)

**Comment by CorvusYe** [comment]
Springboot 的启动类需要加包扫描：@SpringBootApplication(scanBasePackages = {"org.nebula.contrib", "项目包名"})

**Comment by CorvusYe** [comment]
会不会是扫描包没有加

**Comment by ZhangJinzhaoGit** [comment]
![image](https://user-images.githubusercontent.com/41096054/208668627-14e7a286-94d9-42cc-bd5c-e251721395d4.png)
![image](https://user-images.githubusercontent.com/41096054/208668772-988d2db6-f05c-4d77-ba38-d9435624b78f.png)
我用demo启动也报这个

**Comment by CorvusYe** [comment]
我看下哈，刚刚没在电脑边上

**Comment by CorvusYe** [comment]
![1671542494929](https://user-images.githubusercontent.com/15630211/208677252-43df000e-0feb-497f-b329-d64317099304.png)
方便在这个方法断点看看吗，这里是注册 bean 的地方

**Comment by ZhangJinzhaoGit** [comment]
![image](https://user-images.githubusercontent.com/41096054/208678461-f4aecacb-ba42-4cea-8490-866253ca0456.png)
我点启动后连这个断点都没有进。。

**Comment by CorvusYe** [comment]
是让人挺费解的... 
如果没有 Swagger2Configuration 呢

**Comment by ZhangJinzhaoGit** [comment]
也不行。。。

**Comment by CorvusYe** [comment]
![image](https://user-images.githubusercontent.com/15630211/208685567-55746bae-80d8-4165-817d-981023183701.png)
试下这个Springboot的入口能不能进断点。
JDK是什么版本。

**Comment by ZhangJinzhaoGit** [comment]
JDK11
![image](https://user-images.githubusercontent.com/41096054/208687736-b3fd9791-4991-4142-9504-d5d3316d3e43.png)

**Comment by CorvusYe** [comment]
当 SpringApplication run 方法被调起：
```mermaid
sequenceDiagram
SpringApplication->>SpringApplication: prepareContext
SpringApplication->>SpringApplication: applyInitializers
      loop initializers
          alt  initializer is NgbatisContextInitializer
              SpringApplication->>NgbatisContextInitializer:  initialize
              NgbatisContextInitializer->>AbstractApplicationContext: addBeanFactoryPostProcessor( NgbatisBeanFactoryPostProcessor)
          end
      end
SpringApplication->>SpringApplication: refreshContext
SpringApplication->>SpringApplication: refresh
SpringApplication->>AbstractApplicationContext: refresh
AbstractApplicationContext->>AbstractApplicationContext: invokeBeanFactoryPostProcessors
AbstractApplicationContext->>PostProcessorRegistrationDelegate: invokeBeanFactoryPostProcessors
PostProcessorRegistrationDelegate->>PostProcessorRegistrationDelegate: invokeBeanFactoryPostProcessors(postProcessors, beanFactory)
      loop 
          alt  processor is NgbatisBeanFactoryPostProcessor
            PostProcessorRegistrationDelegate->>NgbatisBeanFactoryPostProcessor:  postProcessBeanFactory
            NgbatisBeanFactoryPostProcessor->>NgbatisBeanFactoryPostProcessor: mapperContext
            NgbatisBeanFactoryPostProcessor->>NgbatisBeanFactoryPostProcessor: registerBean
          end
      end
```

可以帮我跟下整个过程是否符合上面的过程吗，
我这边正常，所以...实在是想不到哪个环境的问题导致的 registerBean 断点进不来。
感谢感谢~

**其中：invokeBeanFactoryPostProcessors 断点会进两次，第二次的时候 postProcessors 才会包含NgbatisBeanFactoryPostProcessor**

**Comment by ZhangJinzhaoGit** [comment]
解决了，我傻了。。
我看那个源码里面有个if的判断是nebula.hosts，读到这个才会去走，我看了下我的，我写的是nebula.address，改了之后就好了。
感谢！

**Comment by CorvusYe** [comment]
那个是为了兼容nacos的判断，避免加载两次导致其中一次读取不到配置信息
