### ISSUE TITLE
无属性的点，怎么match查询关联点呢？

### ISSUE THREAD

**Issue by zhangxs0110** [nebula-contrib/ngbatis#113]
CREATE TAG t1();
 INSERT VERTEX t1() VALUE "a":();
 INSERT VERTEX t1() VALUE "b":();
 INSERT VERTEX t1() VALUE "c":();
 INSERT VERTEX t1() VALUE "d":();
 
 CREATE EDGE e1();                 
 INSERT EDGE e1 () VALUES "a"->"b":();  
 INSERT EDGE e1 () VALUES "b"->"c":();  
 INSERT EDGE e1 () VALUES "c"->"d":();  

请问，怎么通过点a查询连接的点b？以及一次性查询点bcd呢？查了许久nsql也没研究出来

**Comment by CorvusYe** [comment]
解决了？方便贴一下解决方案吗

**Comment by zhangxs0110** [comment]
match (v)-[e:e1]->(v2) where id(v)="a" return id(v2)

**Comment by zhangxs0110** [comment]
match p=(v)-[e:e1]->(v2) where id(v)="a" return nodes(p)

**Comment by CorvusYe** [comment]
嗯嗯，同时查 b c d 可以使用：
```sql
 GET SUBGRAPH WITH PROP 3 STEPS FROM "a"        
 BOTH e1
 YIELD VERTICES AS nodes, EDGES AS relationships
```

```sql
MATCH (n: t1)-[r*1..3]-(n2: t1)
WHERE id(n) == 'a'
RETURN n2;
```

**Comment by zhangxs0110** [comment]
![image](https://user-images.githubusercontent.com/30280161/209117192-2343b1b4-c132-42a9-b62a-8941abbf5cf7.png)
这个位置应该是有方向的吧?   ->    不然相反方向传参也会是true

**Comment by zhangxs0110** [comment]
![image](https://user-images.githubusercontent.com/30280161/209118001-a1917355-e41b-44ff-be6a-321f90b09ded.png)
还有个问题，dao层方法参数String类型，到xml层用 $p0 接收不到是什么原因呢

**Comment by CorvusYe** [comment]
这个接口主要是针对无向关系，左向关系或者右向关系，目前需要自己在 xml 中实现一下，
如果不介意也可以 fork 后进行拓展后提 Pull Request
