### ISSUE TITLE
查询结果返回 实体类  报类转换异常

### ISSUE THREAD

**Issue by zhangxs0110** [nebula-contrib/ngbatis#115]
![image](https://user-images.githubusercontent.com/30280161/209765771-1df505c9-a429-463f-a990-45f51bc1e3bc.png)
![image](https://user-images.githubusercontent.com/30280161/209765805-4f55287d-2f6d-4eb1-8756-c5ab8ccde8bc.png)
![image](https://user-images.githubusercontent.com/30280161/209765909-965a74af-68a2-46a9-a337-c0a7e1603f12.png)

**Comment by CorvusYe** [comment]
方便贴一下 ObjVertexDao 不

**Comment by wey-gu** [comment]
> 方便贴一下 ObjVertexDao 不

大叶老师注意身体呀 ❤

**Comment by zhangxs0110** [comment]
![image](https://user-images.githubusercontent.com/30280161/209891978-f2fb8a42-1c8e-4799-bb5d-2621da4b32e6.png)
使用ngbatis自带的基类也是报这个错误，重写selectById方法还是报错

**Comment by zhangxs0110** [comment]
![image](https://user-images.githubusercontent.com/30280161/209892177-899d1a79-a6f0-4ccc-b75a-916367340fa6.png)

**Comment by zhangxs0110** [comment]
数据中有name属性和没有name属性报错一样。我上面贴的数据中没有name属性，之前试了加上属性也是一样的

**Comment by zhangxs0110** [comment]
找到原因了，需要将原项目中的热部署去掉
![image](https://user-images.githubusercontent.com/30280161/209897693-3c1bbc32-9ae4-4caf-adc9-7157a653aa2c.png)

**Comment by CorvusYe** [comment]
可以看看热部署时的ClassLoader，ENV.classLoader也可以修改ngbatis的类加载器，类加载器一致也可以规避无法强转的问题
