### ISSUE TITLE
请问find path的返回结果该怎么映射呢

### ISSUE THREAD

**Issue by yiyi3681** [nebula-contrib/ngbatis#118]
nebula> FIND SHORTEST PATH FROM "player102" TO "team204" OVER * YIELD path AS p;
+--------------------------------------------+
| p                                          |
+--------------------------------------------+
| <("player102")-[:serve@0 {}]->("team204")> |
+--------------------------------------------+
像这样返回结果是长度不确定的路径该怎么办呢，没有在demo里找到对应的实体，想请教一下，谢谢

**Comment by CorvusYe** [comment]
Hi @yiyi3681 
针对Path类型目前是返回nebule-client原生的`PathWrapper`，
这个问题会跟#103 一并处理，定义一个易于获取具体值的通用数据对象。
争取在下周前单独提一个PR

**Comment by yiyi3681** [comment]
看到了您的PR，谢谢开发者们的支持，什么时候能够merge到仓库呢

**Comment by CorvusYe** [comment]
@yiyi3681 已经完成合并，并发布snapshot仓库 [ngbatis-1.1.2-SNAPSHOT](https://s01.oss.sonatype.org/content/repositories/snapshots/org/nebula-contrib/ngbatis/1.1.2-SNAPSHOT/)

**Comment by yiyi3681** [comment]
👍
