### ISSUE TITLE
多标签数据映射问题

### ISSUE THREAD

**Issue by zb139407** [nebula-contrib/ngbatis#120]
![微信图片_20230111161136](https://user-images.githubusercontent.com/62243886/211752490-37b4c450-d748-411d-9ea3-dc16c6e43bf3.png)
当一个VID存在多个tag时，是否可以获取resultType上的tag；如果是默认取第一个，则其他的tag数据无法映射上

**Comment by CorvusYe** [comment]
是的，目前的版本还不支持多标签。
这个功能列在#101 `Vertex multi labels support.` 作为计划内待开发的功能。

**Comment by CorvusYe** [comment]
> ![微信图片_20230111161136](https://user-images.githubusercontent.com/62243886/211752490-37b4c450-d748-411d-9ea3-dc16c6e43bf3.png) 当一个VID存在多个tag时，是否可以获取resultType上的tag；如果是默认取第一个，则其他的tag数据无法映射上

两个标签对应的实体是否存在继承关系，方便描述下这里两个类的关系吗

**Comment by zb139407** [comment]
大概什么时候能出这个功能

**Comment by zb139407** [comment]
>两个标签对应的实体是否存在继承关系，方便描述下这里两个类的关系吗

两个标签没有继承关系，当前需求有一个主标签：企业，四个普通标签，一个节点会有主标签：企业、多个普通标签

**Comment by CorvusYe** [comment]
> 两个标签没有继承关系，当前需求有一个主标签：企业，四个普通标签，一个节点会有主标签：企业、多个普通标签

多标签的特性已经合并，可以试试让普通标签的实体类继承主标签的实体类，
这样普通标签在selectById的时候可以同时赋值当前实体类属性跟主标签实体类属性，
目前的缺点是没有办法赋值其他三个普通标签的属性，只能主标签+一个普通标签
