### ISSUE TITLE
XML文件里面支持<if> <foreach>这种语法吗

### ISSUE THREAD

**Issue by ZhangJinzhaoGit** [nebula-contrib/ngbatis#121]
如题，谢谢！

**Comment by CorvusYe** [comment]
Hi @ZhangJinzhaoGit 
支持类似的语法，形式上不太一样，可以参考：
- [条件控制](https://corvusye.gitee.io/ngbatis-docs/#/?path=dev-example&file=parameter-if&v=v1.1.0-rc)
- [循环语句](https://corvusye.gitee.io/ngbatis-docs/#/?path=dev-example&file=parameter-for&v=v1.1.0-rc)

**Comment by ZhangJinzhaoGit** [comment]
两个问题问一下：
1. where id in (<foreach collection="tagQuery.idList" item="id" separator=","> #{id} </foreach>)
这种好像不支持吗？

**Comment by ZhangJinzhaoGit** [comment]
谢谢！

**Comment by CorvusYe** [comment]
> 两个问题问一下： 1. ![image](https://user-images.githubusercontent.com/41096054/211820440-6e82023f-124d-4121-8228-d46ec72703ff.png)
> 
> 这种好像不支持吗？

如果tagQuery在 dao 中使用了 `@Param("tagQuery")`可以试试：`where id in $tagQuery.idList`

**Comment by CorvusYe** [comment]
> 

类型的限定会比较严格，目前不支持用String来接收数字类型的值

**Comment by ZhangJinzhaoGit** [comment]
我想在if里面判断一个数组的长度大于0或者不为空可以吗

**Comment by CorvusYe** [comment]
> 我想在if里面判断一个数组的长度大于0或者不为空可以吗

可以的：
```xml
 @if (isNotEmpty(tagQuery.idList) ) {
    <!-- 不为空时需要实现的内容 -->
 @}
```

**Comment by ZhangJinzhaoGit** [comment]
where id in $tagQuery.idList
我使用上面这种好像并没有生效
![image](https://user-images.githubusercontent.com/41096054/211830063-0113252b-01ce-4f72-90ae-a9fb1e64c9d6.png)

**Comment by ZhangJinzhaoGit** [comment]
然后我换成 where id(n) in [ ${ ng.join( @ids, ", ", "ng.valueFmt" ) } ] 这样，好像会报错无此属性
![image](https://user-images.githubusercontent.com/41096054/211830763-1bdf881d-f39c-47a1-aad9-d5a1d734beb3.png)

**Comment by CorvusYe** [comment]
方便贴一下 Dao 方法的声明吗

**Comment by ZhangJinzhaoGit** [comment]
![image](https://user-images.githubusercontent.com/41096054/211833564-fed78ca3-0863-4ebd-8e62-4a3a9dffeb23.png)

**Comment by ZhangJinzhaoGit** [comment]
![image](https://user-images.githubusercontent.com/41096054/211833785-63865a89-9439-459c-8af0-1ef50df34a42.png)

**Comment by ZhangJinzhaoGit** [comment]
还有 ng.join 这个方法只能对String的数组使用吗，对Long的数组可以使用吗？谢谢！

**Comment by CorvusYe** [comment]
ng.join List<Long> 可以使用
不好意思，刚刚这里写错了，tagQuery 前面需要用 `@` 符来标记是个 java 对象
```xml
  @if ( isNotEmpty( @tagQuery.idList) ) {
    <!-- 不为空时需要实现的内容 -->
  @}
 ```

**Comment by ZhangJinzhaoGit** [comment]
![image](https://user-images.githubusercontent.com/41096054/211835942-859db30c-d007-41c9-93e2-31786d1c13e1.png)
我发现不加@是好的，加了就会报错，说找不到这个。。



然后ng.join我在使用的时候，如果是List<Long>会报错
![image](https://user-images.githubusercontent.com/41096054/211836650-ad82bc4f-248f-44fc-a815-bbe0e0921b0e.png)

**Comment by CorvusYe** [comment]
> 然后ng.join我在使用的时候，如果是`List<Long>`会报错 ![image](https://user-images.githubusercontent.com/41096054/211836650-ad82bc4f-248f-44fc-a815-bbe0e0921b0e.png)

如果是数字可以把 ng.join 的第三个参数 `"ng.valueFmt"` 去掉

**Comment by ZhangJinzhaoGit** [comment]
可以了，感谢，最后一个问题问一下
MATCH p=(v:tag01) -[e:edge01*1..1]-(v2:tag01)
我想里面的某一个值是变量，支持吗
MATCH p=(v:tag01) -[e:edge01*1..$tagQuery.length]-(v2:tag01)
这样会报语法错误
![image](https://user-images.githubusercontent.com/41096054/211842106-b4ecb088-ebcf-4c10-a57b-f010f03d0826.png)

**Comment by CorvusYe** [comment]
可以用：`MATCH p=(v:tag01) -[e:edge01*1..${tagQuery.~size}]-(v2:tag01)`

**Comment by ZhangJinzhaoGit** [comment]
> 可以用：`MATCH p=(v:tag01) -[e:edge01*1..${tagQuery.~size}]-(v2:tag01)` 或者：`MATCH p=(v:tag01) -[e:edge01*1..${@tagQuery.size()}]-(v2:tag01)`

length是tagQuery这个类的一个成员变量

**Comment by CorvusYe** [comment]
哦哦，大意了
`MATCH p=(v:tag01) -[e:edge01*1..${tagQuery.length}]-(v2:tag01)`

`${ 变量名 }` 是执行到数据库前读取的，
`$变量名` 是执行到数据库后，由数据库获取的
如果 nebula 的多跳能支持参数的方式，上面的语句可以用 $变量 来替代

**Comment by ZhangJinzhaoGit** [comment]
可以了，感谢！

**Comment by CorvusYe** [comment]
ng.join 的方法签名：
```java
   public String call(Iterable<?> iterable, String sep, String fnName)
```
按理`List<Long>`也应该支持 `ng.valueFmt`，也感谢你帮忙发现了一个 `ng.join` 的 bug。
