### ISSUE TITLE
Field setters in org.nebula.contrib.ngbatis.binding.DefaultArgsResolver required a bean of type 'java.util.List' that could not be found.

### ISSUE THREAD

**Issue by yiyi3681** [nebula-contrib/ngbatis#126]
***************************
APPLICATION FAILED TO START
***************************

Description:

Field setters in org.nebula.contrib.ngbatis.binding.DefaultArgsResolver required a bean of type 'java.util.List' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'java.util.List' in your configuration.

运行失败报了上述错误，可以帮忙看看嘛

**Comment by CorvusYe** [comment]
可以在项目中加个类: 
```java
@Component 
public class VoidSetter implements Setter<Void> { 
    @Override 
    public Object set(Void param) {
        return null; 
    } 
}
```

具体情况可以参考＃99

**Comment by yiyi3681** [comment]
可以了，谢谢~
