### ISSUE TITLE
About releasing the new version v1.1.2 after #130 merged.

### ISSUE THREAD

**Issue by CorvusYe** [nebula-contrib/ngbatis#131]
as title.

**Comment by yiyi3681** [comment]
大概什么时候能发布新版本呢？

**Comment by CorvusYe** [comment]
如果合并顺利的话，应该就会尽快发布~

**Comment by CorvusYe** [comment]
> 大概什么时候能发布新版本呢？
@yiyi3681 
新版本已发布 [ngbatis-1.1.2](https://s01.oss.sonatype.org/content/repositories/releases/org/nebula-contrib/ngbatis/1.1.2/)
如果暂时下载不了，是Maven不同镜像间同步需要一段时间。
