### ISSUE TITLE
是否支持自定义配置数据库文件

### ISSUE THREAD

**Issue by ben981113** [nebula-contrib/ngbatis#135]
是否支持将：
nebula:
  hosts: 127.0.0.1:19669, 127.0.0.1:9669
  username: root
  password: nebula
  space: test
  pool-config:
    min-conns-size: 0
    max-conns-size: 10
    timeout: 0
    idle-time: 0
    interval-idle: -1
    wait-time: 0
    min-cluster-health-rate: 1.0
    enable-ssl: false
的配置信息不放在application.yml 下 而是放在其他文件中

**Comment by CorvusYe** [comment]
目前支持的配置方式与 springboot 2.x 是一样的，支持按不同环境分文件配置，支持配置中心
