### ISSUE TITLE
there's some code style check error for snapshot deploy

### ISSUE THREAD

**Issue by Nicole00** [nebula-contrib/ngbatis#138]
please see https://github.com/nebula-contrib/ngbatis/actions/runs/4214924039/jobs/7315711308 to check the code style issue, thanks.

**Comment by CorvusYe** [comment]
I fixed in this commit: [9761ed0](https://github.com/nebula-contrib/ngbatis/pull/137/commits/9761ed06176a00d363d113becae42eb62779bdd9)

**Comment by Nicole00** [comment]
thanks
