### ISSUE TITLE
想询问下不明确插入的字段和Tag标签应该如何自定义nsql

### ISSUE THREAD

**Issue by hejiahuichengxuyuan** [nebula-contrib/ngbatis#14]
```java
/**
     * 批量插入点语句
     * @author: BT-BOX
     * @param tagName       tag名称
     * @param vidKey        vid的key
     * @param params        插入的字段
     * @param dataList      插入的数据
     * @version: 1.0
     * @createDate: 2022/8/23 10:14
     * @return: void
     */
    void batchInsertVertex(@Param("tagName") String tagName,
                           @Param("vidKey") String vidKey,
                           @Param("params") Set<String> params,
                           @Param("dataList") List<Map<String, Object>> dataList);
```

- xml

```xml
<mapper
        namespace=
                "ye.weicheng.ngbatis.demo.repository.GraphBaseApiNgMapper"
>

    <insert id="batchInsertVertex" >
        INSERT VERTEX ${tagName}
         (
            @for ( param in params ) {
                ${param},
            @}
         )

        VALUES
        @for ( datas in dataList ) {
         '${ datas.${vidKey}}' : ('${datas.name}', ${datas.age}, '${datas.id}')

        @}
        ;
    </insert>

</mapper>
```

- 这是我的nsql插入语句，其中 ${param}, 逗号我不明白应该如何去掉最后一个逗号。
- `${ datas.${vidKey}}` 是那个 vertx 的 vid值，这样应该是错误的不清楚怎么弄

**Comment by hejiahuichengxuyuan** [comment]
有没有if判断变量类型的呢？因为我不清楚字段的类型所以无法添加 单引号 ''

**Comment by CorvusYe** [comment]
1. 关于去掉最后一个逗号，可以使用先通过获取循环下标位来判断是否最后一个 `paramLP.last` 其中 param 是for循环的变量  ：
```diff
      @for ( param in params ) {
-         ${param},
+        ${param} ${ paramLP.last ? '' : ',' }
      @}
```
参考：[循环语句](https://www.kancloud.cn/xiandafu/beetl3_guide/2138952)

2. 关于怎么获取 vid 的问题，循环的当前元素 datas 是一个 Map，可以通过在变量前加一个 `@` 符号来表示接下来要执行的表达式是 java 方法，然后Map实例中有 get 方法可以通过 key 来获取值，所以咱们所需要做的改动就是：
```diff
        @for (datas in dataList) {
-         '${datas.${vidKey}}' : ('${datas.name}', ${datas.age}, '${datas.id}')
+        '${@datas.get(vidKey)}' : ('${datas.name}', ${datas.age}, '${datas.id}')
        @}
```
参考：[函数调用](https://www.kancloud.cn/xiandafu/beetl3_guide/2138956)

3. 关于类型判断，可以使用函数：`type.name` 来判断: 例如：
```
${type.name( datas.name ) == 'String' ? ("'" + datas.name + "'") : datas.name }
```
参考：[函数调用](https://www.kancloud.cn/xiandafu/beetl3_guide/2138956)

**Comment by CorvusYe** [comment]
没有理解错的话，你这边先完成的功能应该是一个通过调用方传参的方式，忽略XXXDao本身schema的限制，动态写入节点，如果属性只有基本的类型，可以使用下列方式：
```
        INSERT VERTEX ${tagName}
         (
            @for ( param in params ) {
                ${param} ${ paramLP.last ? '' : ',' }
            @}
         )
        VALUES
        @for ( datas in dataList ) {
            '${@datas.get(vidKey)}' : (
            @for ( param in params ) {
                ${type.name( @datas.get( param ) ) == 'String' ? ("'" + @datas.get( param ) + "'") : @datas.get( param ) } ${ param LP.last ? '' : ',' }
            @}
            )  ${ datasLP.last ? '' : ',' }
        @}
        ;
```

**Comment by CorvusYe** [comment]
没有理解错的话，你这边先完成的功能应该是一个通过调用方传参的方式，忽略XXXDao本身schema的限制，动态写入节点，如果属性只有基本的类型，可以使用下列方式：
```
        INSERT VERTEX ${tagName}
         (
            @for ( param in params ) {
                ${param} ${ paramLP.last ? '' : ',' }
            @}
         )
        VALUES
        @for ( datas in dataList ) {
            '${@datas.get(vidKey)}' : (
            @for ( param in params ) {
                ${type.name( @datas.get( param ) ) == 'String' ? ("'" + @datas.get( param ) + "'") : @datas.get( param ) } 
                ${ paramLP.last ? '' : ',' }
            @}
            )  ${ datasLP.last ? '' : ',' }
        @}
        ;
```

**Comment by hejiahuichengxuyuan** [comment]
你的理解是正确的！十分感谢大佬抽出时间回答我这个问题！但是我无法确定 Object类型，因为我是 postgresql 动态查询出来的 Map<String, Object>。目前我的想法是先找出表的字段类型，然后再由后端去一一对应转换成Java类型，再拼接成 VALUES后面的字符 到 xml中完成动态插入

**Comment by CorvusYe** [comment]
有点客气了哦。还得感谢你给我提供思路呢。
无法确定的类型，如果你是线下自己迁移数据用的，可以等我中午提交的pr merge以后的版本。
里面提供了一些函数可以用。
比如说：`${ ng.valueFmt( your_param ) }` 调用的时候就可以不需要关注字段应不应该加单引，要不要做 date格式处理，这些在新的版本就可以通过使用函数，开发者忽略掉，而交由ngbatis处理。
再比如说：`${ ng.join( params ), ', ' } ` 也可以不需要关心最后一个逗号要不要加。
如果传进来的是一个 Map，可以通过 `ng.kv` 函数获得三个列表：`columns`、`values`、`valueNames`，例子如下：
- param
  ```json
  {
     "name": "Tom",
     "age": 8
  }
  ```
- xml
  ```cql
  @var kv = ng.kv( param );
  INSERT VERTEX `${ tagName }` {
    ${ ng.join( @kv.columns, ", ", "ng.schemaFmt" ) }
  }
  VALUES ${ ng.valueFmt( @param.get( vidKey ) ) } : {
    ${ ng.join( @kv.values ) }
  }
  ```
近期还会再提交一个版本来完善这个[pr#18](https://github.com/nebula-contrib/ngbatis/pull/18)，有兴趣可以留意一下合并状态跟版本发布。

**Comment by hejiahuichengxuyuan** [comment]
好的。更新之后请告知我一下，我迫不及待使用该新功能了

**Comment by CorvusYe** [comment]
OK ~

**Comment by CorvusYe** [comment]
@hejiahuichengxuyuan 
新版本[1.1.0-rc](https://s01.oss.sonatype.org/content/repositories/releases/org/nebula-contrib/ngbatis/1.1.0-rc/)更新了，增加了一些内置函数可以在 xml 中使用：
- ng.valueFmt
  > 对不定类型的数据值进行格式化，忽略是否追加单引号及日期格式化，直接传原始 java类型即可

  参数位 | 参数说明 | 类型  | 是否必传 | 默认值
  ---|---|---|---|---
  1 | 值 | Object | Y | 
  2 | 如果是字符串是否在前后追加 .* 形成模糊查询 | boolean | N | false

- ng.schemaFmt
  > 对模式名前后追加 **`**，以避免与数据库关键字冲突

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 模式名，如 tagName, edgeName, propertyName | Object | Y

- ng.tagName
  > 用于从实体类或Dao接口获取 tag name

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 与Schema对应的实体类对象 | Object | Y 
  2 | 类模型，使用 `ng_cm` 传入 | ClassModel | N | null



- ng.pkField
  > 用于获取 主键属性，java.lang.reflect.Field

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 实体类类型 | Class<?> | Y 
  2 | 如果不存在主键是否报错中断 | Boolean | N | false

- ng.pkName
  > 用于获取 主键名，String

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 实体类对象 | Object | Y 
  2 | true 时使用列名，false 时使用属性名 | Boolean | N | true

- ng.entityType

  > 用于获取实体类类型

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 实体类对象 | Object | Y 

- ng.fieldNames
  > 获取属性名集合（不包括主键）

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 实体类对象 | Object | Y 
  2 | true 时使用列名，false 时使用属性名 | Boolean | N | true
  
- ng.id
  > 获取id值

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 实体类对象 | Object | Y 
  2 | 如果不存在主键是否报错中断 | Boolean | N | true
  3 | 如果值为空，true会通过主键生成器返回新值，false 时 返回空 | Boolean | N | true
  
- ng.kv
  > 通过实体对象或者获取多个集合
  > - columns 列名集合
  > - valueNames 属性名集合
  > - values 值集合
  > - types 属性类型

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 实体类对象 | Object | Y 
  2 | 参数名前缀 | String | N | null
  3 | 是否排除主键 | Boolean | N | true
  4 | 是否排除空值 | Boolean | N | true
  5 | 如无主键，是否报错中断 | Boolean | N | true
  
- ng.join
  > 对集合进行格式化

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 待格式化的集合 | Iterable | Y 
  2 | 元素间的分隔符 | String | N | `,` 
  3 | 函数名，各元素拼接前，可进行函数名指定的格式化函数先行格式化，再拼接 | String | N | null


- ng.ifStringLike
  > 类型为字符串时，前后拼接 `.*`

  参数位 | 参数说明 | 类型 | 必传 | 默认值
  ---|---|---|---|---
  1 | 值 | Object | Y 
  2 | 属性类型 | Object | N | null
  3 | 属性名，用于不将值明文写在 ngql 中，而使用参数名，让 nebula 在参数中取值 | String | N | null

**Comment by hejiahuichengxuyuan** [comment]
感谢大佬还记得，想问问动态 spaceName 那块功能已经实现了吗？

**Comment by CorvusYe** [comment]
关于 space 的问题，在 mapper 下指定，或者其子标签下指定都可以。
```
<mapper namespace="..." space="spaceName">
    <select space="spaceName">
    </select>
</mapper>
```

**Comment by hejiahuichengxuyuan** [comment]
maven 包无法下载

**Comment by CorvusYe** [comment]
那可能需要等明天再看看，可能几个 maven 仓库之间的包未同步，我看发布的位置是有这个版本包了https://s01.oss.sonatype.org/content/repositories/releases/org/nebula-contrib/ngbatis/

**Comment by CorvusYe** [comment]
@hejiahuichengxuyuan 
同步了 https://search.maven.org/artifact/org.nebula-contrib/ngbatis/1.1.0-rc/jar 
[阿里云仓库](https://developer.aliyun.com/mvn/search)也能找到

**Comment by hejiahuichengxuyuan** [comment]
好的，已经可以更新了，谢谢你的无私贡献
