### ISSUE TITLE
是否支持传入一个Map对象给SQL

### ISSUE THREAD

**Issue by ZhangJinzhaoGit** [nebula-contrib/ngbatis#142]
如题，我现在有一个Map，我想向图数据库查询的时候，在XML的sql中根据Map的键值来取值

**Comment by CorvusYe** [comment]
支持的～

**Comment by ZhangJinzhaoGit** [comment]
麻烦请教一下，在XML中怎么使用呢

**Comment by CorvusYe** [comment]
比如说:
```java
  selectByMap(Map param);
```

```xml
  <select id="selectByMap">
       MATCH (n:person) 
       WHERE n.person.name == '${name}'
       RETURN n
  </select>
```

name是Map里的一个key

**Comment by ZhangJinzhaoGit** [comment]
![image](https://user-images.githubusercontent.com/41096054/221892938-e015e60e-767f-4be6-b8be-103fd836c1d8.png)
![image](https://user-images.githubusercontent.com/41096054/221893008-2346f302-8610-4fb5-8689-f3ae42aa50b9.png)
叶老师，这样可以吗

**Comment by ZhangJinzhaoGit** [comment]
实现了，谢谢！map["1"] 就可以

**Comment by CorvusYe** [comment]
如果想用get方法过去，前面需要加个`@` 符号，
key是1的值，是个集合是吧

**Comment by CorvusYe** [comment]
> 实现了，谢谢！map["1"] 就可以

OK～你发现了一个我自己没用过的用法，哈哈哈
