### ISSUE TITLE
修改遇到点或边找不到问题

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#146]
修改点或边时，因为id生成器的原因，导致传入的id参数被新生成的id给覆盖，应该怎么解决呢

**Comment by CorvusYe** [comment]
https://github.com/nebula-contrib/ngbatis/blob/master/src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/IdFn.java#L58

可以在这个地方断点看下吗，这是唯一一处通过主键生成该主键值的地方

**Comment by zhangxk-ocean** [comment]
打断点后，程序没有走到断点这，直接结束

**Comment by zhangxk-ocean** [comment]
是调用update()方法进行修改吧，截图如下：
![image](https://user-images.githubusercontent.com/132866381/236737365-173d7661-767b-40d8-b5ea-74d715961960.png)
![image](https://user-images.githubusercontent.com/132866381/236737193-e140cad5-3194-4b28-b1de-e6881f900000.png)
![image](https://user-images.githubusercontent.com/132866381/236737222-a4164972-3b92-4a51-a51c-495531dadb93.png)
![image](https://user-images.githubusercontent.com/132866381/236737260-34c5ede3-5ec2-4372-a98c-98febe6bc21b.png)

**Comment by zhangxk-ocean** [comment]
我是在实体类中直接声明vid作为id，不是name，然后再tag中没有创建vid，然后报的这个错，这个vid还需要创建吗

**Comment by zhangxk-ocean** [comment]
这个问题解决了，接参有问题，谢谢
