### ISSUE TITLE
Ngbatis文档中心地址变了吗

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#154]
https://corvusye.github.io/ngbatis-docs/#/?path=quick-start&file=about&v=v1.1.0-rc
打开报404

**Comment by CorvusYe** [comment]
对的，昨晚刚做的升级。
https://graph-cn.github.io/ngbatis-docs/

**Comment by zhangxk-ocean** [comment]
haode
