### ISSUE TITLE
failed to start: `'cup.biz.kg.dao.TagBasicMapper' that could not be found.`

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#155]
1. 报错信息：
Description:
Parameter 0 of constructor in cup.biz.kg.service.impl.TestServiceImpl required a bean of type 'cup.biz.kg.dao.TagBasicMapper' that could not be found.
Action:
Consider defining a bean of type 'cup.biz.kg.dao.TagBasicMapper' in your configuration.

2.配置信息
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/8336e125-dcbc-450c-b53c-cf2e3cb1a4ef)
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/cd862ad7-cb2f-4938-abab-5f72bdf69d6c)
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/768a3354-9d51-457b-b601-d0fcf42bf6d9)
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/5775f6ca-079e-4001-ab50-55e54f88aa30)

**Comment by zhangxk-ocean** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/b554ad33-5c4e-4b54-a166-854c514c33f9)
xml文件里面是写了一个createTag语句

**Comment by CorvusYe** [comment]
项目根目录有 asm-debug 的目录生成吗

**Comment by zhangxk-ocean** [comment]
没有

**Comment by CorvusYe** [comment]
在这个地方断点看下这个报错的 mapper 的信息，  [    loadClassCode(classModelEntry);](https://github.com/nebula-contrib/ngbatis/blob/8b6b9d5d3d52a3ce5359a8165d947f2610185f10/src/main/java/org/nebula/contrib/ngbatis/proxy/RamClassLoader.java#L36)

**Comment by zhangxk-ocean** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/acbea72c-40a3-4813-9544-394574f2e531)
应该是没走到这

**Comment by CorvusYe** [comment]
那往上一行断点，按理开始读取 bean 了，这步已经走完了，那最大的可能是 这个 map 是空的，还是扫描的位置出了问题

**Comment by CorvusYe** [comment]
或者在这个位置端点，直接看扫描得到了哪些内容：https://github.com/nebula-contrib/ngbatis/blob/8b6b9d5d3d52a3ce5359a8165d947f2610185f10/src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java#L78

**Comment by zhangxk-ocean** [comment]
有点奇怪，直接就结束了

**Comment by CorvusYe** [comment]
啊啊啊...
那只能直接断点在入口了https://github.com/nebula-contrib/ngbatis/blob/8b6b9d5d3d52a3ce5359a8165d947f2610185f10/src/main/java/org/nebula/contrib/ngbatis/NgbatisContextInitializer.java#L28

springboot是什么版本

**Comment by zhangxk-ocean** [comment]
没看版本
断点在入口就行了，要看什么呢
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/87d2c292-c210-46d7-adde-dae2965ed7ec)

**Comment by CorvusYe** [comment]
会不会跟这个问题是一样的 https://github.com/nebula-contrib/ngbatis/issues/111 只是猜测哈

**Comment by zhangxk-ocean** [comment]
感觉这个是扫描包出的问题
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/0975ade5-deb4-4ad2-8f4b-af8fe85714c0)
zhelia这俩注解一起用也没问题吧，我试了试其他的项目，也没事

**Comment by CorvusYe** [comment]
我也没这么写过诶，回头验证下，配置中心用的是啥，nacos 吗，把配置放到配置中心看看？

**Comment by zhangxk-ocean** [comment]
配置中心用的nacos，配置就放在了nacos里

**Comment by zhangxk-ocean** [comment]
我试了下，把Mapper和mapper.xml删掉，就能正常启动了，因为mapper报的错

**Comment by CorvusYe** [comment]
nebula.pool-config.min-conns-size = 0 ?
这个值改成正的试试，让一启动就连接数据库，排除一下配置没读到的问题
之后再来排查是不是 bean 没扫描到的问题

**Comment by zhangxk-ocean** [comment]
这个值设置的是2

**Comment by zhangxk-ocean** [comment]
报错的原因应该是是mapper调用不到mapper.xml里面的方法

**Comment by zhangxk-ocean** [comment]
或者是service层调用mapper.java里的方法时报的错

**Comment by CorvusYe** [comment]
是动态代理的过程没执行。代理类没生成，asm-debug 这个文件夹没生成的话，也说明 jvm 中没有接口对应的实现类

**Comment by zhangxk-ocean** [comment]
看到了，里面的nebulaPool的值是原始值，然后我就把nacos配置放到了bootstrap配置文件中，启动成功了，问题就是没有加载nacos里的配置，这是什么原因呢

**Comment by CorvusYe** [comment]
两次 if 前读取的配置都是原始值吗的吗？这个我还得再跟下

**Comment by zhangxk-ocean** [comment]
这是因为没有加载到nacos的配置

**Comment by CorvusYe** [comment]
这边配置读取用的是 ConfigurableEnvironment 的接口， Springcloud 用的也是这个接口。

> 这是因为没有加载到nacos的配置

所以是项目搭建的问题？是的话，记得来记录下解决的过程哈

**Comment by zhangxk-ocean** [comment]
哈哈，也是个简单的问题，namespace错了，导致配置没加载上

**Comment by CorvusYe** [comment]
看来是解决了？可以可以~

**Comment by zhangxk-ocean** [comment]
解决了
