### ISSUE TITLE
How to print NebulaGraph query failures?

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#156]
现在执行nGQL报错后，都是一种报错
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/85bc605e-06e9-49b4-b0e8-607eae0213d1)
很难排查是哪里的原因

**Comment by CorvusYe** [comment]
是用了 1.1.2 的版本，并且 nebula.ngbatis.use-session-pool: true 了吗

**Comment by zhangxk-ocean** [comment]
nebula.ngbatis.use-session-pool: true这个配置没有加

**Comment by zhangxk-ocean** [comment]
加上这个配置，还是报一样的错

**Comment by zhangxk-ocean** [comment]
这样的

**Comment by CorvusYe** [comment]
那你帮断点看下具体是哪个空了，回头我把详细的报错信息补上

**Comment by CorvusYe** [comment]
当然，直接提PR更好～哈哈哈😀

**Comment by zhangxk-ocean** [comment]
不行，直接到这报错的，不知道上一步是哪

**Comment by CorvusYe** [comment]
翻了下，72行这个接口现在的版本并没有直接使用，包括代理类用的也不是这个
因为是公开方法，担心有项目会直接用，只是早期 api 的一个遗留
调用到这里属实有点不好理解

**Comment by zhangxk-ocean** [comment]
怎么更换1.2.0版本的呢，我加上repositories标签后，不走repositories标签，还是去从私服拉取依赖，结果就是拉取不到

**Comment by CorvusYe** [comment]
那不用，只要有个 `@Bean` 的方法能返回一个 Env 实例就行，我想下怎么处理会好点

**Comment by CorvusYe** [comment]
想了下，自己写 `@Bean` 注解的方法，感觉也跟自己重写个 EnvConfig 差不多...

**Comment by zhangxk-ocean** [comment]
哈哈
