### ISSUE TITLE
参数循环问题

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#159]
@for 怎么实现循环之间加一个逗号呢
类似这种：(), (), ()

**Comment by CorvusYe** [comment]
有个ng.join的函数可以用

**Comment by zhangxk-ocean** [comment]
可以这个举个例子吗，不会用欸
@for ( entry in p ) {
    @if ( isNotEmpty( entry.value ) ) {
        AND n.person.`${ entry.key }` == $p.${ entry.key }
    @}
@}

**Comment by CorvusYe** [comment]
可以看看这个https://graph-cn.github.io/ngbatis-docs/dev-example/built-in-function.html

**Comment by CorvusYe** [comment]
https://github.com/nebula-contrib/ngbatis/blob/master/src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/JoinFn.java

看一下函数对应的java方法签名这部分的使用可能就会好理解一点

**Comment by CorvusYe** [comment]
> 可以这个举个例子吗，不会用欸 @for ( entry in p ) { @if ( isNotEmpty( entry.value ) ) { AND n.person.`${ entry.key }` == p.{ entry.key } @} @}

dao.java
```java
  List<Person> selectByPerson(@Param("p") Person a);
```
```xml
    <select id="selectByPerson" resultType="ye.weicheng.ngbatis.demo.pojo.Person">
        MATCH (n: person)
        WHERE 1 == 1
        @for ( entry in p ) {
            @if ( isNotEmpty( entry.value ) ) {
                AND n.person.${ entry.key } == $p.${ entry.key }
            @}
        @}
        RETURN n
    </select>
```

test.java
```java
    Person p = new Person();
    p.setName("叶小南");
    p.setAge(18);
    List<Person> persons = repository.selectByPerson(p);
```

最终执行的效果等价于：
```sql
:param p => {"name":"叶小南","age":18};

MATCH (n: person)
WHERE 1 == 1 
  AND n.person.name == $p.name
  AND n.person.age == $p.age
RETURN n
```

不同位置的 p 虽然都代表传入的参数，但是意义不同：
![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/9f9bc27e-48b1-46b2-a31a-67e3cf8d93a6)
- 第一处（左侧）是我们自己给参数的命名
- 第二处（右侧for部分）是给字符串模板用的
- 第三处（右侧and部分）是给数据库用的

两个`$`符号的意义也不同，
- `$p` 是数据库的参数标识符，代表从这里开始从参数读取，是 nGQL 语法的一部分
- `${ entry.key }`，`${ }` 是字符串模板的参数定界符，不是 nGQL 语法的一部分

在这个例子中，`$p.${ entry.key }` 的最终结果是 `$p.name` 共同组成 nGQL 语法的一部分，执行到数据库中。
