### ISSUE TITLE
内置参数问题

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#160]
想实现动态新增点数据，创建接参类，属性包括vid、tagName、map类型的properties，怎么使用内置参数取出来propitious呢
我看例子是@var kv = ng.kv( ng_args[0], '', true, true );
如果只按这种方式，取出来的kv是空

**Comment by CorvusYe** [comment]
你可以试试这个：

- dao.java
```java
   void insertDynamic( Map<String, Object> map );
```

- xml，（标签我就不写了哈）
```sql
    @var kv = ng.kv( properties );
    INSERT VERTEX IF NOT EXISTS 
    `${ tagName }` (
        ${ ng.join( @kv.columns ", ", "ng.schemaFmt" ) }
    )  ${ vid } : (
        ${ ng.join( @kv.values ) }
    );
```

**Comment by CorvusYe** [comment]
这个是接口单参数的写法，如果是多参数，或者加了 `@Param` 读取map的key值，需要带上对应的前缀。

单参数的情况下，实体类跟Map的参数，会把内部的属性或 key 形成的参数名提升到顶级，不需要带 p0

**Comment by zhangxk-ocean** [comment]
好的

**Comment by CorvusYe** [comment]
> 想实现动态新增点数据，创建接参类，属性包括vid、tagName、map类型的properties，怎么使用内置参数取出来propitious呢 我看例子是@var kv = ng.kv( ng_args[0], '', true, true ); 如果只按这种方式，取出来的kv是空

这边提到的自建了接参类，如果想用上内置参数，可以用`@var kv = ng.kv( ng_args[0].properties );` 试试
这里的需求更想获取的是 properties 的 kv 值

**Comment by zhangxk-ocean** [comment]
![image](https://github.com/nbula-contrib/ngbatis/assets/132866381/b932a550-7fc5-417d-96e3-fc7f92b85681)
没有获取到id，接参类加id注解了
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/47b92f18-d202-4a94-a6e3-94050012c9c2)
是因为没有加Table注解的原因吗

**Comment by zhangxk-ocean** [comment]
我是想用上id生成器的，不知道为什么直接${vid}娶不到值，不过用这个就行了，@var id = ng.id( ng_args[0] );

**Comment by CorvusYe** [comment]
是个好思路。
ng.kv 函数的方法签名：
```java
Object call(Object entity, String prefix, Boolean excludePk, Boolean selective, Boolean idRequired)
```
excludePk 默认是 true, 显然这个场景下，我们也不希望 values 中包含 id 的值，会与数据库栏位不符。

**Comment by zhangxk-ocean** [comment]
对

**Comment by CorvusYe** [comment]
你用得好深啊，有空了要不要写篇文章投稿到社区，哈哈哈
cc: @QingZ11

**Comment by zhangxk-ocean** [comment]
文笔不行，哈哈

**Comment by wey-gu** [comment]
写吧，写完了 ChatGPT 帮忙润色！

**Comment by zhangxk-ocean** [comment]
如果使用这种方式新增多条数据，又该怎么写呢

**Comment by zhangxk-ocean** [comment]
或者直接在service层遍历

**Comment by CorvusYe** [comment]
可以加一层`@for`包裹，但是数量上会有一些限制，但整体会比在service里面写快很多

**Comment by zhangxk-ocean** [comment]
我试试

**Comment by CorvusYe** [comment]
service注意控制单次写入的数量
之前测过的数据来看
属性不多的话，一次写入2000条问题不大
没办法控制属性长度的话，500条相对会是比较稳妥
可以根据实际运行情况进行调整

**Comment by zhangxk-ocean** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/fdfca3f4-7c7b-45c4-8ed0-7ade9dcd0533)
这指的是什么错误呢

**Comment by CorvusYe** [comment]
list 用的是参数名，`@Param("list")`，如果没有加的话，使用 `p0` 代替 list
另外 ng_args[0] 需要换成 v

**Comment by zhangxk-ocean** [comment]
明白了

**Comment by zhangxk-ocean** [comment]
这是不能直接用ng.id吗
![Uploading image.png…]()

**Comment by CorvusYe** [comment]
不确定是不是for里不能声明变量的原因，我看看先

**Comment by CorvusYe** [comment]
> ![image](https://user-images.githubusercontent.com/132866381/240559029-b87da814-ba70-49da-903d-06fea19f0f22.png) 不行欸

这个不行的原因是，这个 v 跟单条执行时的 ng_args[0] 不一样了，是被转换过的 JSONObject，不是自建的接参类
最原始的 java 对象，还是得从内置对象中获取

**Comment by CorvusYe** [comment]
一直在等之前立的 [flag](https://github.com/nebula-contrib/ngbatis/blob/master/CHANGELOG.md) 写完再发
结果卡在第一步了...

**Comment by zhangxk-ocean** [comment]
emmm

**Comment by CorvusYe** [comment]
> 1.2.0版本的什么时候可以发布呢

刚刚提了一个关于发布1.1.3的议题正在审核，可以看看包含的新内容能不能满足你对新版本的期望
