### ISSUE TITLE
新增边报错

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#161]
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/7835d585-3e43-4b4a-899b-5e8a3cf8c613)
这是什么原因呢

**Comment by CorvusYe** [comment]
试试转义 `\@0`，对模板来是说 `@` 是个特殊符

**Comment by zhangxk-ocean** [comment]
明白了

**Comment by zhangxk-ocean** [comment]
成功

**Comment by CorvusYe** [comment]
[Beetl 1.23 Escape](https://www.kancloud.cn/xiandafu/beetl3_guide/2138965)

**Comment by zhangxk-ocean** [comment]
嗯，这个文档得多研究研究

**Comment by zhangxk-ocean** [comment]
有个nebula语句想请教一下，
查询指定rank的语句：FETCH PROP ON `serve` "11111"->"22222"@1 YIELD edge as e;
现在就是这个rank有0,1,2三个值了，怎么把这3条边都给查出来呢

**Comment by CorvusYe** [comment]
`@rank` 这部分是可选的

**Comment by zhangxk-ocean** [comment]
怎么选呢，查看官方文档没找到，是指定rank，还是指定范围呢

**Comment by CorvusYe** [comment]
直接去掉试试？（其实我也不熟，一般用match😂）

**Comment by zhangxk-ocean** [comment]
我也换成match了，直接where加条件多简单，哈哈

**Comment by CorvusYe** [comment]
是否比较简单只是相对使用习惯而言啦，问题不大。
ps: 解决了的问题帮忙close一下哈
