### ISSUE TITLE
About releasing v1.1.3

### ISSUE THREAD

**Issue by CorvusYe** [nebula-contrib/ngbatis#162]
@wey-gu @Nicole00 
About releasing a 1.1.3 version 
to fix the problem that space config in yml does not work in sessionPool, 
and space containing white space support.
and, can I just directly switch from 3.4.0 to 3.5.0

**Comment by wey-gu** [comment]
I think @CorvusYe laoshi could always just create releases without confirming with others.

What do you think? @Nicole00 @CorvusYe ?

**Comment by CorvusYe** [comment]
OK~ I will create another PR to publish this version.
