### ISSUE TITLE
查询列表报空指针

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#164]
查询列表报错，可能是什么原因呢
xml语句：
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/1e6d409c-1673-4859-a512-4997ecc13feb)
参数：
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/54aa02bb-69f2-4833-8820-0096f51d674b)

**Comment by CorvusYe** [comment]
有具体的日志吗

**Comment by CorvusYe** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/7341ceaa-b65d-4682-a4d8-26629ab9c7a4)
提一个跟空指针没关系的，这部分可以考虑使用以下来替代：
```
and src.${tagName}.${prop.propertyName} ${ng.ifStringLike(prop.propertyValue)}
```

**Comment by zhangxk-ocean** [comment]
替换以后，还是报一样的错，日志如下：

**Comment by zhangxk-ocean** [comment]
这个空指针异常找到问题根源了，不小心把接参类型写成了long，用Long就行了

**Comment by zhangxk-ocean** [comment]
现在报个新问题，是什么原因呢：
![image](https://github.com/nebula-contrib/ngbatis/assets/132866381/ba900b84-6e04-44d2-9071-f4a738a67cf2)

**Comment by CorvusYe** [comment]
for in的位置直接跟参数名就好了，不用$取值

**Comment by zhangxk-ocean** [comment]
明白了
