### ISSUE TITLE
springboot2.7.7 引入ngbatis1.1.3 启动报错

### ISSUE THREAD

**Issue by LETMECALM** [nebula-contrib/ngbatis#167]
- maven依赖
<img width="554" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/4f14a422-59ee-4d20-a41e-a8d3ec1df684">

- yml配置（用的默认配置，改了hosts，测试能连接库）
<img width="840" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/de674d04-058d-47f4-9967-9a796e5d0038">

- 包扫描
<img width="1265" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/be9dcc97-3b23-4e17-90e2-70354f3ea685">

- 错误信息
<img width="1320" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/f3dbff9d-217b-4cec-8867-a09bbbac361e">

- 初步debug
<img width="1269" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/d59cc436-716b-41cc-bfaa-2278ee41c9a3">

没有找到原因，求助!!

**Comment by CorvusYe** [comment]
可以查一下继承了基类的DAO使用的主键类型有没有指定 `extends NebulaDaoBasic<FileInfo, 主键类型>`

**Comment by LETMECALM** [comment]
<img width="1214" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/e331370f-0606-493d-8f81-bcca9df03892">

**Comment by LETMECALM** [comment]
<img width="1214" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/2050e708-02c5-4b52-ac2b-7518a6db617f">

项目中还用到mysql，orm框架用的Pigx，生成器会自动`exends PigxBaseMapper` ，这样应该指定不了主键类型，这两个框架能兼容共用吗

**Comment by CorvusYe** [comment]
可以兼容使用，不过 xml 的位置需要重新指定，避免冲突
```xml
cql:
  parser:
    # 更换开发者自定义的 xml 所在位置
    mapper-locations: ng-mapper/**/*.xml # 默认为 mapper/**/*.xml
```

**Comment by LETMECALM** [comment]
<img width="1293" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/b55e58f7-7dfd-4871-9b4d-b012fb65a50e">

改了配置还是同样的错误，应该是没生效，我配置有问题吗

**Comment by LETMECALM** [comment]
自定义mapper位置在 docs 里面有吗，我怎么没找到

**Comment by CorvusYe** [comment]
有的，https://graph-cn.github.io/ngbatis-docs/step-forward-docs/advanced-configuration.html
```yml
cql:
  parser:
    # 更换开发者自定义的 xml 所在位置
    mapper-locations: ng-mapper/**/*.xml # 默认为 mapper/**/*.xml

nebula:
   ...
```

**Comment by LETMECALM** [comment]
<img width="1385" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/f5585222-fad9-42ba-a1ed-ac2a5b7d0ad5">

路径没找到，配置里要写绝对路径吗

**Comment by CorvusYe** [comment]
不需要写绝对路径哦
截图中ngmapper的路径是：com/nlz/.../ngmapper
配置里的路径是需要将 ngmapper 建到 resources 目录下
可以没有 xml 文件

**Comment by LETMECALM** [comment]
<img width="1275" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/45167548/c383c0e3-dbdd-4858-945e-de6b5d02baa4">

`resources` 下也建了`ngmapper` 文件夹，也是报错的

**Comment by CorvusYe** [comment]
大意了😂
刚刚debug了一下，还是需要有xml文件

**Comment by LETMECALM** [comment]
可以了，没有xml文件应该也可以启动（一点拙见，哈哈）

**Comment by CorvusYe** [comment]
> 可以了，没有xml文件应该也可以启动（一点拙见，哈哈）

是的，直觉上也应该是这样。不过之前没留意这个资源加载的机制，没文件直接认为 `ngmapper/` 是一个文件资源了，而没有当做目录获取空列表。回头我再看看怎么改合适。
发现了新问题，赞赞赞~
