### ISSUE TITLE
批量写入单条数据报错

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#169]
批量写入1000点数据就会报错，调用的单条数据插入，前面几百条正常，后续异常
![企业微信截图_1686229299554](https://github.com/nebula-contrib/ngbatis/assets/132866381/0efbfe5e-8d33-471d-b733-4775b17c9ddf)

**Comment by CorvusYe** [comment]
-Xss2m
启动参数可以加一下这个

**Comment by zhangxk-ocean** [comment]
解决了
