### ISSUE TITLE
当标注了错误的edge后，Mapper的 insertEdge方法阻塞无法执行

### ISSUE THREAD

**Issue by charle004** [nebula-contrib/ngbatis#178]
当调用Mapper的 insertEdge方法时，如果 Edge的实体类的注解 @Table中的name指定了错误的 edge名，即图空间中不存这样的edge时，程序会阻塞无法执行

**Comment by charle004** [comment]
我中间更换了Space空间的名称， 导致@Space(name = "xx")  指定的老的图空间不存在，所以也可能是 指定了不存在的图空间名称 导致的

**Comment by CorvusYe** [comment]
新旧空间都是存在的吗，只是新指定的空间不存在对应的 edgeType ?

**Comment by CorvusYe** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/48c99ad2-b209-46c8-8c59-91de35ec6bd9)
我这边试了下不存在的 edgeType 是能正常报错中断。



> 我中间更换了Space空间的名称， 导致@space(name = "xx") 指定的老的图空间不存在，所以也可能是 指定了不存在的图空间名称 导致的

这边的意思是跟 edgeType 没关系，而跟不存在的图空间有关系吗

**Comment by charle004** [comment]
抱歉，是我在线程池任务中没有处理到这个异常 误判了...

**Comment by CorvusYe** [comment]
hahaha，没问题了就行~
