### ISSUE TITLE
xml里， @if调用isNotEmpty判定字符串非空异常

### ISSUE THREAD

**Issue by xljnc** [nebula-contrib/ngbatis#184]
mapper代码：
<img width="644" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/25718197/b8dfe060-31de-4b3c-ac43-b11695fbbee5">
xml代码如下：
<img width="468" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/25718197/581029ba-7eb7-4dff-88b4-c243c2bee887">
如果传入的fromVertexId为null，@if判定字符串非空为true，输出结果
<img width="802" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/25718197/bba6aacf-d1ef-4b70-944d-f7c467c26c78">
如果xml改为如下（去掉${ fromVertexId }的单引号‘’）
<img width="533" alt="image" src="https://github.com/nebula-contrib/ngbatis/assets/25718197/7e66e525-ba14-41d5-a4e2-036cb18f1d89">
nql执行报错
>>10:08:17:缺少符号(PARSER_MISS_ERROR):isNotEmpty 位于4行 资源:
        MATCH (v1)-[e :${ edgeType }]->(v2)
        WHERE 1 == 1
        @if ( isNotEmpty( ${ fromVertexId } ) ) {
        and id(v1) == '${ fromVertexId }'
        @}
        RETURN count(e)
    

缺少输入 ) 在 'isNotEmpty' 后面
1|
2|        MATCH (v1)-[e :${ edgeType }]->(v2)
3|        WHERE 1 == 1
4|        @if ( isNotEmpty( ${ fromVertexId } ) ) {
5|        and id(v1) == '${ fromVertexId }'
6|        @}
7|        RETURN count(e)
麻烦解答下这个问题，非常感谢。

**Comment by CorvusYe** [comment]
把${}去掉 直接写变量试试看？

**Comment by xljnc** [comment]
问题解决
