### ISSUE TITLE
Vertex必须有非@Id的属性才能正确生成insert语句

### ISSUE THREAD

**Issue by xingsheq** [nebula-contrib/ngbatis#190]
按下面定义生成的sql如下，不带tag，必须再定义一个属性才能正确生成sql
@Data
@Table(name = "host")
@Space(name = "xx")
public class HostVertex{

    @Id
    String name;
}

sql:
        INSERT VERTEX IF NOT EXISTS 
        VALUES 'aaaaaaaaa' : (
            
        );

**Comment by CorvusYe** [comment]
问题已重现，考虑不周了😂。今明两天修复。flag先立～
