### ISSUE TITLE
已经使用mybatis的项目引入ngbatis校验mapper方法导致项目启动不了

### ISSUE THREAD

**Issue by IndexNull** [nebula-contrib/ngbatis#193]
报错信息:java.lang.IllegalArgumentException: 接口 com.chinatelecom.common.mapper.ElasticSearchMapper 中，未声明 xml 中的出现的方法：RowKeyResultMap
报错截图：
![1691115396722](https://github.com/nebula-contrib/ngbatis/assets/50311169/6683fa5f-dcdb-41d2-8cf3-822f07eb5cfa)

求问，怎么配置可以不让ngbatis去扫其他包的xml，只对ngbatis的包的xml mapper等信息进行校验

**Comment by q451234** [comment]
请问是怎么解决的

**Comment by CorvusYe** [comment]
> 请问是怎么解决的

@q451234 可以试着指定一下 xml 的位置 https://github.com/nebula-contrib/ngbatis/blob/master/docs%2FzhCn%2Fmd%2Fstep-forward-docs%2Fadvanced-configuration.md
