### ISSUE TITLE
mapper和xml文件绑定不上

### ISSUE THREAD

**Issue by IndexNull** [nebula-contrib/ngbatis#195]
启动没有问题
调用的时候会报Invalid bound statement (not found): com.********.nebula.mapper.NodeMapper.queryNode

配置截图
![企业微信截图_169113836211](https://github.com/nebula-contrib/ngbatis/assets/50311169/a4baa2ed-1d84-45f4-81ec-68ab17fd705b)
![企业微信截图_1691138999155](https://github.com/nebula-contrib/ngbatis/assets/50311169/40017708-1d55-405e-b3e3-66fe10502825)

![企业微信截图_16911387978400](https://github.com/nebula-contrib/ngbatis/assets/50311169/c90276a8-63b1-47ce-917e-4bbb9014e78b)
麻烦看看还需要修改什么配置吗

**Comment by IndexNull** [comment]
> xml里面有标签id是queryNode不

![企业微信截图_16911390807297](https://github.com/nebula-contrib/ngbatis/assets/50311169/30916bef-6bdb-4b16-8e50-5956f3113b98)
有的

**Comment by CorvusYe** [comment]
那可以检查一下mapper的namespace的指向

**Comment by IndexNull** [comment]
> 那可以检查一下mapper的namespace的指向

这个namespace也没有问题   NodeMapper我看到项目启动的时候也代理成功了

**Comment by CorvusYe** [comment]
Invalid bound statement (not found)
没记错的话，这个提示应该是 mybatis-plus 的提示，可以检查下 NodeMapper 是否在 mbp 的扫描范围内，
记得把这个接口排除在 mbp 的扫描范围之外

**Comment by CorvusYe** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/330b8216-f07e-497e-9d9f-f0cac2d74d09)

**Comment by IndexNull** [comment]
可以啦 ，原来是被mybatis扫到了  想再问个问题 
![企业微信截图_16911402864459](https://github.com/nebula-contrib/ngbatis/assets/50311169/e5e9e663-65fb-4fca-a23b-1c1178bdef58)
阿里云的环境我应该配置哪个端口地址呀

**Comment by IndexNull** [comment]
> ![image](https://user-images.githubusercontent.com/15630211/258374657-330b8216-f07e-497e-9d9f-f0cac2d74d09.png)

可以啦 ，原来是被mybatis扫到了     想再问个问题阿里云的环境我应该配置哪个端口地址呀
![企业微信截图_1691140550340](https://github.com/nebula-contrib/ngbatis/assets/50311169/31cf45ee-d528-4281-a73d-5a67d1c3a8b9)

**Comment by CorvusYe** [comment]
可以同时配几个地址：
我自己是同机部署，直接配了这样的。
```yml
nebula:
  hosts: 127.0.0.1:9669,127.0.0.1:19669,127.0.0.1:19670
```
就看服务跟数据库的连通性了，我自己的习惯是：本地回环ip > 内网ip > 公网ip

**Comment by IndexNull** [comment]
![企业微信截图_16911407657256](https://github.com/nebula-contrib/ngbatis/assets/50311169/929d9b29-968d-4be4-8c5c-b469dac40366)
查询报错  是因为我服务地址配置错误了吗

**Comment by IndexNull** [comment]
> 可以同时配几个地址： 我自己是同机部署，直接配了这样的。
> 
> ```yaml
> nebula:
>   hosts: 127.0.0.1:9669,127.0.0.1:19669,127.0.0.1:19670
> ```
> 
> 就看服务跟数据库的连通性了，我自己的习惯是：本地回环ip > 内网ip > 公网ip

![image](https://github.com/nebula-contrib/ngbatis/assets/50311169/378f1862-1b63-4cc6-87c0-059d1fbd5fc1)
查询报错 是因为我服务地址配置错误了吗

**Comment by CorvusYe** [comment]
ping 得通吗，先 ping 一下确定下连通性，不通的话可以看看安全组出入站规则是否开了对应端口

**Comment by IndexNull** [comment]
> ping 得通吗，先 ping 一下确定下连通性，不通的话可以看看安全组出入站规则是否开了对应端口

可以啦  谢谢你的帮助  新手上路嘿嘿
