### ISSUE TITLE
$p0参数注入报错

### ISSUE THREAD

**Issue by IndexNull** [nebula-contrib/ngbatis#196]
![1691231737313](https://github.com/nebula-contrib/ngbatis/assets/50311169/2f70ac6f-482f-4cb5-b52a-ca1954cbfa09)
![1691231757804](https://github.com/nebula-contrib/ngbatis/assets/50311169/ba57b4d4-ec9a-419a-979d-6e55c5616cd1)
![1691231813419](https://github.com/nebula-contrib/ngbatis/assets/50311169/1510cf8e-974c-41f5-819d-136eaad5c592)

$p0报错，翻看以前的issue
![1691231551310](https://github.com/nebula-contrib/ngbatis/assets/50311169/36111407-cece-41a7-adff-d473a1958633)
使用这两种也报错

**Comment by CorvusYe** [comment]
控制台的输出是怎么样的

**Comment by IndexNull** [comment]
> 控制台的输出是怎么样的

![1691232418030](https://github.com/nebula-contrib/ngbatis/assets/50311169/188becba-b255-4254-9efa-f6435eec64a5)
![1691232478843](https://github.com/nebula-contrib/ngbatis/assets/50311169/31c49590-7b3a-45b2-9e56-b01b72176e4e)
tableName传的 player

**Comment by CorvusYe** [comment]
参数是SCHEMA的话，注意一下引号的区别，使用 斜引号：`

**Comment by CorvusYe** [comment]
```sql
   DESCRIBE TAG `${ p0 }`
```

**Comment by IndexNull** [comment]
> ```sql
>    DESCRIBE TAG `${ p0 }`
> ```

可以了  谢谢啦   祝你有个愉快的周末

**Comment by CorvusYe** [comment]
哈哈谢谢～
