### ISSUE TITLE
insert Vertex 对象为map,如何实现

### ISSUE THREAD

**Issue by sunchunhuihub** [nebula-contrib/ngbatis#198]
insert Vertex 对象为map,如何实现

**Comment by CorvusYe** [comment]
https://github.com/nebula-contrib/ngbatis/issues/14

可以看看这个 issue 是否能满足需求，里面有使用 map 做 insert Vertex 的实现

**Comment by CorvusYe** [comment]
如果#14里面的接口不满足需求，可以贴一下想要的接口格式，我看看怎么写 xml 比较合适

**Comment by sunchunhuihub** [comment]
就是insertVertex(String tagName,String  vidKey, Map<String,Object> data)

**Comment by CorvusYe** [comment]
可以试试这个
```xml
    <insert id="insertVertex">
        @var kv = ng.kv( p2, '', true, true );
        @var tagName = ng.tagName( ng_args[0] );
        INSERT VERTEX IF NOT EXISTS `${ p0}` (
            ${ ng.join( @kv.columns, ", ", "ng.schemaFmt" ) }
        )
        VALUES ${ ng.valueFmt( p1 ) } : (
            ${ ng.join( @kv.values ) }
        );
    </insert>
```

如果觉得 p0、p1... 不直观，可以试着给参数加 `@Param('tagName')` 这样的注解

**Comment by sunchunhuihub** [comment]
我的vidKey是主键属性呢

**Comment by CorvusYe** [comment]
可以指定主键生成器

**Comment by sunchunhuihub** [comment]
就是我的主键就想用数据中的，通过vidKey取

**Comment by sunchunhuihub** [comment]
对了这个会不会已有的mybatis冲突

**Comment by CorvusYe** [comment]
哦哦，懂了，
比如说：
```java
insertVertex( 'tagName', 'id', { 'tagName': 'player', 'id': 'player100', 'name': 'Yao Ming' } );
```
调用方式是这样的不。

> 对了这个会不会已有的mybatis冲突

可以兼容，但是要改默认配置
https://graph-cn.github.io/ngbatis-docs/step-forward-docs/advanced-configuration.html#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9-xxxdao-xml-%E7%9A%84%E4%BD%8D%E7%BD%AE

需要注意的是，NgBatis 的 Mapper 需要再 MyBatis 的 Mapper扫描范围之外，不然会被 MyBatis 所代理，但是又在关系型数据库中找不到对应的表，就会有问题

**Comment by sunchunhuihub** [comment]
是这个意思，这种怎么实现

**Comment by CorvusYe** [comment]
可以试试这个，map 的值会因为 remove 被修改，如果是不希望被修改的话，ng.json 就需要换成自己实现 for 循环

```java
  void insertVertex(
    @Param("tagName") String tagName, 
    @Param("idName") String idName, 
    @Param("data") Map<String,Object> data
  );
```

```xml
    <insert id="insertVertex">
        @var id = @data.remove(idName);
        @var tag = @data.remove(tagName);
        @var kv = ng.kv( data, '', true, true );
        INSERT VERTEX IF NOT EXISTS `${ tag }` (
            ${ ng.join( @kv.columns, ", ", "ng.schemaFmt" ) }
        )
        VALUES ${ ng.valueFmt( id ) } : (
            ${ ng.join( @kv.values ) }
        );
    </insert>
```

**Comment by sunchunhuihub** [comment]
好的，
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/4a6fa3cd-c088-470c-8ada-f3cc806b712d)

这种配置d对吗

**Comment by CorvusYe** [comment]
这样配置可能就不支持子文件夹，如果需要子文件夹，可以改成：ng-mapper/**/*.xml

**Comment by CorvusYe** [comment]
使用非实体写入，之前也有对应的方案：
https://github.com/nebula-contrib/ngbatis/blob/547b003d14cca2ea411da2504d3bc8b47fcca16d/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/TestRepository.java#L81-L113
https://github.com/nebula-contrib/ngbatis/blob/547b003d14cca2ea411da2504d3bc8b47fcca16d/ngbatis-demo/src/main/resources/mapper/TestRepository.xml#L146-L155

**Comment by sunchunhuihub** [comment]
我这没有子文件夹，就是放在ng-mapper里的，和mybatis的mapper做个区分

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/0a78f9b3-7408-47ec-92f7-120358c28604)
感觉还是bei被mybatis识别了

**Comment by CorvusYe** [comment]
有MapperScan的注解？

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/0852fa0e-3bf3-45ec-b907-caef43859197)

但是有报错

**Comment by CorvusYe** [comment]
https://github.com/nebula-contrib/ngbatis/issues/195
可以参考这个的文件结构跟注解方式

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/47fcf031-5b67-4f98-96c1-31e01a68bef4)

还bao报错

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/28a6a39f-5b2d-4048-95c2-e5fd34186405)
我直接f放一个就可以吧

**Comment by CorvusYe** [comment]
只放一个的话，有一些基本的配置信息会丢失

**Comment by CorvusYe** [comment]
有MyBatis，那你应该是有其他的数据源，应该是不能排除其他数据源的
https://graph-cn.github.io/ngbatis-docs/quick-start/install.html#%E9%A1%B9%E7%9B%AE%E4%B8%AD%E8%BF%98%E6%9C%89%E5%85%B6%E4%BB%96%E6%95%B0%E6%8D%AE%E5%BA%93

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/6d09c32f-0a14-4461-8581-95b7249d556b)
这里我写这个没问题吧

**Comment by CorvusYe** [comment]
"org.nebula.contrib" 还是需要的

**Comment by sunchunhuihub** [comment]
好的，另外再问个问题，分页方式必须得继承公共的dao吗

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/d3f1b2ee-3c6c-42d4-afef-d05118b8926b)
我配置的是nebula为啥要扫到我的mybatis的mapper

**Comment by CorvusYe** [comment]
> 好的，另外再问个问题，分页方式必须得继承公共的dao吗

不需要的，只要参数里有 org.nebula.contrib.ngbatis.utils.Page 类型就可以

**Comment by CorvusYe** [comment]
> ![image](https://user-images.githubusercontent.com/45676598/259974161-d3f1b2ee-3c6c-42d4-afef-d05118b8926b.png) 我配置的是nebula为啥要扫到我的mybatis的mapper

项目中的 MyBatis 扫描范围是怎么样的，建议在后面带上 `.*.mapper`，这样就可以排除 `ngmapper` 的接口

**Comment by sunchunhuihub** [comment]
这个我看是ngbatis扫描报的错，他把mybatis的mapper扫描出来了

**Comment by CorvusYe** [comment]
不应该啊，现在的版本 ngbatis 的接口代理都是根据 mapper.xml 里的 namespace 来指定的，跟扫描没有关系

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/88918119-60ac-4596-8882-eaa6edb047b1)
看下这个

**Comment by CorvusYe** [comment]
> 好的， ![image](https://user-images.githubusercontent.com/45676598/259962850-4a6fa3cd-c088-470c-8ada-f3cc806b712d.png)
> 
> 这种配置d对吗

哦哦，知道了，这个配置没生效，cql: 需要顶格

**Comment by sunchunhuihub** [comment]
哦，他和nebula是一个层级对吧

**Comment by CorvusYe** [comment]
对的

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/3c00d16d-6eb6-475e-b5ac-e29215b19d50)
改完了，mybatis的mapper报错了，注入不了

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/ce6db363-4a73-42a2-846c-833c4971daab)
我这边只扫描nebula的mapper

**Comment by CorvusYe** [comment]
> ![image](https://user-images.githubusercontent.com/45676598/259979874-ce6db363-4a73-42a2-846c-833c4971daab.png) 我这边只扫描nebula的mapper

`@MapperScan( value = {"com.nancal.nebula.*.mpper"} )`

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/edee9b5f-81a0-44b1-adf1-cccfd0c225c3)
报错了，少一层文件夹

**Comment by sunchunhuihub** [comment]
你们明天在吗

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/bbd6e746-9b4f-4002-9fed-27b62983cc4f)
奇怪还是这个错误，弄完，mabatis的mapper不行了

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/ad1c953d-e248-48a2-867e-1841ffb1619d)
这是我们自己的mapper

**Comment by CorvusYe** [comment]
哦哦，你的文件结构是这样的啊，那直接用`@MapperScan( value = {"com.nancal.mapper"} )`

这个指定的是mybatis的扫描，不是ngbatis的，只是为了避免重复代理导致报错

**Comment by sunchunhuihub** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/45676598/c3d53983-0cf7-4df3-a2e3-59516e2de29e)
改了，之后报nebula的xml错误

**Comment by sunchunhuihub** [comment]
我看不需要docType把

**Comment by sunchunhuihub** [comment]
加个微信好友把，我这赶鸭子上架，需要大神支持

**Comment by CorvusYe** [comment]
ngbatis 用的不是 SAXParse，不需要 docType 的...
但是我又不确定哪里的配置又让这个  QueryNebulaMapper 被 MyBatis 扫描到了..

**Comment by CorvusYe** [comment]
> ![image](https://user-images.githubusercontent.com/45676598/259983273-c3d53983-0cf7-4df3-a2e3-59516e2de29e.png) 改了，之后报nebula的xml错误

这个问题产生的原因是：mybatis.mapper-locations=classpath:**/*.xml 指定的范围扫描到了 ng-mapper 下的 xml
进而被当成 mybatis 的 xml 来解析了，所以产生了这个错误

配置 mybatis.mapper-locations 时需要把 ng-mapper 下的 xml 排除在外，
如上文件结构可以使用：mybatis.mapper-locations=classpath:mapper/*.xml

如果使用 mybatis-plus:
```yml
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
```

明确 mybatis 扫描的范围，进而避免出现上面的错误
