### ISSUE TITLE
Transfer to Nebula-Contrib Org

### ISSUE THREAD

**Issue by wey-gu** [nebula-contrib/ngbatis#2]
Dear @CorvusYe,

Could you please help transfer this repo to https://github.com/Shinji-IkariG, who is the admin of the Org, then he will transfer it to the Org?

@Shinji-IkariG kindly help invite @CorvusYe to the org.

Thanks!

**Comment by CorvusYe** [comment]
This repo has been transferred to @Shinji-IkariG.
Hope it can get better and better in Nebula.
So happy that I have this chance to help some people now or in the future.
Thanks for you at the same time. @wey-gu

**Comment by Shinji-IkariG** [comment]
This repo has been transferred to @nebula-contrib.
Thank you for your contribution to the community.

**Comment by wey-gu** [comment]
Dear @CorvusYe 

This is what open-source is all about, we jointly contribute what we consider meaningful, and it helps others all around the world with your magic!!!

It's really great to have you, the amazing @CorvusYe in the community.

Hopefully, we got more attention for ngbatis under this nebula-contrib tent so that more guys out there could contribute and benefit from your work! 

Thanks again!
