### ISSUE TITLE
vid为Long的demo

### ISSUE THREAD

**Issue by Peter-Chou** [nebula-contrib/ngbatis#200]
请问下是否能简单提供下vid为Long的demo？

**Comment by CorvusYe** [comment]
在现有demo的基础上，大概需要两个改动: 

1. https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/TestRepository.java#L27-L27

这边接口的实现最后一个泛型换成Long，`NebulaDaoBasic<T, Long>`

2. 指定主键生成时，返回Long类型

**Comment by Peter-Chou** [comment]
好哒谢谢啦

**Comment by CorvusYe** [comment]
不客气～
