### ISSUE TITLE
ng.valueFmt的使用

### ISSUE THREAD

**Issue by IndexNull** [nebula-contrib/ngbatis#202]
我有个需求就是                                                                                                                                                                             
          match (v:`${ params.tagValue }`)
          where v.`${ params.tagValue }`.`${ params.paramEn }` == ${ ng.valueFmt(params.paramValue) }
          return count(v)      参数我是不知道类型的所以入参的时候给的string，但是如果图库存的是int的话是查不到的  这种情况fmt这里能解决吗  或者说有别的更好的方式做这种需求吗

**Comment by CorvusYe** [comment]
这种情况按习惯应该是什么类型的，传什么类型的值进行查询，以约定为主，传参的时候约定好，如果是请求查阅时再获取schema信息判断类型，会造成不必要的网络开销，比较不建议

**Comment by IndexNull** [comment]
好的  明白了
