### ISSUE TITLE
使用ALL(e_ in e ）语句  内部使用条件判断 报错   缺少输入在 ')' 后面， 期望 '>>'

### ISSUE THREAD

**Issue by IndexNull** [nebula-contrib/ngbatis#203]
![企业微信截图_16922804048913](https://github.com/nebula-contrib/ngbatis/assets/50311169/ecf3afbf-7ac8-4285-a979-979842120279)

报错：缺少输入在 ')' 后面， 期望 '>>'
1|
2|
3|            MATCH (v) -[e*1..${ ng.valueFmt(params.step)]-> (v2)
4|            WHERE v.`${ params.sourceTag }`.entity_value == ${ ng.valueFmt(params.sourceEntityValue) }
5|            AND   v.`${ params.sourceTag }`.entity_type == ${ ng.valueFmt(params.sourceEntityType) }
6|            AND
7|            ALL(e_ in e

**Comment by CorvusYe** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/c5cf437e-1217-42a2-b43e-674dd95f7e9c)

可以先试试这个改法行不行

**Comment by IndexNull** [comment]
> ![image](https://user-images.githubusercontent.com/15630211/261340139-c5cf437e-1217-42a2-b43e-674dd95f7e9c.png)
> 
> 可以先试试这个改法行不行

这个可以了  我还有一个问题  我这个ALL里面还有个list的条件需要循环去取，但是list内部条件是or 和外部的是and 要怎么拼呢  拼半天了  有点头疼

**Comment by CorvusYe** [comment]
是个二维的集合吗 [ [], [], [] ]

**Comment by IndexNull** [comment]
> 是个二维的集合吗 [ [], [], [] ]

["000","001-001","002-003"]这种

**Comment by CorvusYe** [comment]
试试 ${ ng.join( 集合 , ' and ' ) } ?

**Comment by CorvusYe** [comment]
if的后半句，试试这个 
` && strutil.length( relationNum ) == 3`

**Comment by IndexNull** [comment]
> 

在前面加个1 != 1 应该可以吧

**Comment by CorvusYe** [comment]
> 在前面加个1 != 1 应该可以吧

可以的，加在 `@for` 前最简洁

**Comment by IndexNull** [comment]
> > 在前面加个1 != 1 应该可以吧
> 
> 可以的，加在 `@for` 前最简洁

谢谢大叶  那么晚还帮我查问题  非常感谢

**Comment by CorvusYe** [comment]
NgBatis 对 nGQL 的动态组装并不会区分是否是点后面的 tag，所以是可以的

>  ![企业微信截图_16923443243339](https://user-images.githubusercontent.com/50311169/261535539-4f421d18-e588-4a72-9576-dfd995adbba2.png)

这边显示的是 nGQL 的语法错误，可以先把符合需求的合法的 nGQL 在 studio / console 验证下再用模板来替换，效果上会好一点~

面向github编程哈哈哈哈，是个有趣的说法~

**Comment by IndexNull** [comment]
@CorvusYe 
![企业微信截图_16928518663793](https://github.com/nebula-contrib/ngbatis/assets/50311169/35ba64e7-07a6-4df2-b36d-045df37bc20c)
大叶拿当前循环的索引是这样拿吗？
![企业微信截图_16928519647566](https://github.com/nebula-contrib/ngbatis/assets/50311169/6ffe279c-3204-4a05-a43a-52612468c642)
怎么我匹配变长边的时候想根据循环取索引匹配每一步边的属性时取不到当前索引

**Comment by CorvusYe** [comment]
缺少了`${}`，`${ 变量LP.dataIndex }`

**Comment by CorvusYe** [comment]
https://www.kancloud.cn/xiandafu/beetl3_guide/content/1.10%E5%BE%AA%E7%8E%AF%E8%AF%AD%E5%8F%A5.md

**Comment by IndexNull** [comment]
> https://www.kancloud.cn/xiandafu/beetl3_guide/content/1.10%E5%BE%AA%E7%8E%AF%E8%AF%AD%E5%8F%A5.md

我就说源码没这些规则啊  我人傻了   没注意看xml依赖的是beetl3
