### ISSUE TITLE
i18n for docs

### ISSUE THREAD

**Issue by wey-gu** [nebula-contrib/ngbatis#206]
as titled

**Comment by wey-gu** [comment]
@CorvusYe would you mind including the doc frontend code in this repo too? 

(I would like to set up a github page to create English docs under the nebula-contrib.org domain like ngbatis.nebula-contrib.org for the English version of docs)

**Comment by CorvusYe** [comment]
I didn't implement it before according to the vitepress i18n documentation, maybe we can try it again.

**Comment by wey-gu** [comment]
Check this out @omar-araboghli , @CorvusYe :-D
