### ISSUE TITLE
Docs: add EXECUTION-PROCESS.md to docs

### ISSUE THREAD

**Issue by wey-gu** [nebula-contrib/ngbatis#226]
I believe the equivalent content of https://github.com/nebula-contrib/ngbatis/blob/master/EXECUTION-PROCESS.md is crucial to users.

**Comment by CorvusYe** [comment]
That's a good idea. Although there are some descriptions of the corresponding sequence diagrams, it would obviously be better to have a textual description as well.
https://corvusye.gitee.io/ngbatis-docs/step-forward-docs/operation-sequence.html

**Comment by wey-gu** [comment]
Yes, this is exactly the much better equivalent, I'll translate those mermaid flowchart instead.
🚀

**Comment by syedzubeen** [comment]
Hey guys,
Can someone elaborate as to what the DoD is, for this PR?
From what I get, we need to add a markdown file to the current docs, but what is the file that needs to go there and what is the content of that file is somewhat unclear to me?

**Comment by CorvusYe** [comment]
Hi @syedzubeen, 
We need to add this file https://github.com/nebula-contrib/ngbatis/blob/master/EXECUTION-PROCESS.md Go to the docs, in the "Learn More" section.
And in the same folder as https://github.com/nebula-contrib/ngbatis/blob/master/docs/en/md/step-forward-docs/advanced-configuration.md. 
And translate it into English.

**Comment by syedzubeen** [comment]
Got it, thank you !

Can you assign me this and I'll get started.

**Comment by CorvusYe** [comment]
I'd be happy to do that.
In addition, merging into this file may be a better choice.
/step-forward-docs/operation-sequence
​
cc: @wey-gu

**Comment by syedzubeen** [comment]
@CorvusYe Can you have a look at the PR and let me know if it looks good?
