### ISSUE TITLE
The testing module does not support automation

### ISSUE THREAD

**Issue by shbone** [nebula-contrib/ngbatis#236]
shoud we Optimize testing And
automatically run schema and tag edge  create scripts for easy testing @wey-gu

**Comment by wey-gu** [comment]
Sure we should have done, but not too late in Hacktoberfest!!!

cc @CorvusYe

**Comment by wey-gu** [comment]
Would you mind contributing to this??

**Comment by CorvusYe** [comment]
> shoud we Optimize testing And automatically run schema and tag edge create scripts for easy testing @wey-gu

This is a great idea and one that has been lacking in the current REPO. Thank you in advance. @shbone

**Comment by shbone** [comment]
I will try to submit PR after Oct. 1st

**Comment by CorvusYe** [comment]
> Would you mind contributing to this??
> 
> Hint: hacktoberfest only count between oct. 1st to 31st :-D, in case you are working on that, please submit PR after 1st October!

What time zone is it in?@wey-gu

**Comment by wey-gu** [comment]
It's likely UTC-12, so on the safe side, we could start from 2nd Oct.

But it's only limited to the PR push time, we could discuss the implementation before the push in ISSUE :D

**Comment by shbone** [comment]
I have finished my automated create `test` graph survey. 
And I think this issue could be closed. 
If this method have something wrong after this, I will update it .
Thank you!@wey-gu

**Comment by zhanghuidinah** [comment]
It seems that the issue has been resolved, please refer to https://github.com/nebula-contrib/ngbatis/pull/239
