### ISSUE TITLE
xml中指明 resultType为 java.util.Map 时程序阻塞不执行

### ISSUE THREAD

**Issue by charle004** [nebula-contrib/ngbatis#243]
日志：
DEBUG o.n.contrib.ngbatis.binding.DefaultResultResolver - 针对java返回类型 java.util.Map 与 xml 返回类型 java.util.Map 的结果集处理器为：org.nebula.contrib.ngbatis.handler.MapResultHandler@416bff93

**Comment by CorvusYe** [comment]
java接口的方法方便贴一下吗？

**Comment by charle004** [comment]
> java接口的方法方便贴一下吗？

sorry我代码的问题
