### ISSUE TITLE
java.lang.ClassCastException[update: caused by hot-reload plugin]

### ISSUE THREAD

**Issue by AhYi8** [nebula-contrib/ngbatis#245]
我用的是SpringCloud集成的；
在项目启动都没什么异常
SQL日志打印也都正常
```sql
- provyMethod: ****.dao.ngbatis.PersonDao$getPersonByPhone
- session space: person_aist
- nGql:
    MATCH (v)
    WHERE v.person.phone == "******"
    RETURN v
    LIMIT 1;

- params: {phone=*******}
- result: ColumnName: [v], Rows: [("id": person{*********})]
```
但是就在接受返回值的时候，一直抛`java.lang.ClassCastException: **.Person cannot be cast to **.Person`，前后两个Person类是同一个包下的同一个类；
请问作者知道是什么原因吗？感谢

**Comment by CorvusYe** [comment]
可以试试在这个地方断点，然后看看以下三行返回的 ClassLoader 是否有所不同
https://github.com/nebula-contrib/ngbatis/blob/ef7c714f18884f1b78ac0910519ade396aa8a2da/src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxyClassGenerator.java#L139-L140

```java
  returnType.getClassLoader();
  mm.getResultType.getClassLoader();
  mm.getMethod().getReturnType().getClassLoader()
```

**Comment by AhYi8** [comment]
此项为空，抛了空指针异常
```
mm.getResultType.getClassLoader();
```
我发现，1.1.5的源码，和你说的不太一样，相同代码所在行数，和逻辑都不太一样

**Comment by AhYi8** [comment]
我又比对了一下，确实有些许的不一样，就 `org.nebula,contrib.ngbatis.NgbatisContextInitializer$readParseCfgProps()`方法的最后一个 `.setResourceRefresh()`
![Snipaste_2023-10-12_14-40-02](https://github.com/nebula-contrib/ngbatis/assets/56581248/2f70733b-e13d-4491-873e-8821e0258989)
这个方法在我的本地的源码里就多了个强制类型转换；
还有你上面说的这个方法里也比我下载的包的源码里多或少了很多强制类型转换；
不知道是打包的时候自动加的，还是啥真有问题？

**Comment by CorvusYe** [comment]
OKOK，可以了就行。
