### ISSUE TITLE
go from语句

### ISSUE THREAD

**Issue by sakuraemiya** [nebula-contrib/ngbatis#249]
你好，我想问一下，我在xml里面写的go from语句是不支持吗

**Comment by CorvusYe** [comment]
不会的，xml方面并不会干涉关于ngql的语义，有对应的错误信息吗

**Comment by sakuraemiya** [comment]
org.nebula.contrib.ngbatis.exception.QueryException: 数据查询失败： 数据查询失败SyntaxError: Parameter is not supported in vid near ` $p'
xml语句&nbsp;go from $p0 over cityHaveOrder yield id($$) as vid&nbsp; &nbsp;是哪里写的有问题吗


光荣
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nebula-contrib/ngbatis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月24日(星期二) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nebula-contrib/ngbatis] go from语句 (Issue #249)





 
不会的，xml方面并不会干涉关于ngql的语义，有对应的错误信息吗

**Comment by CorvusYe** [comment]
看着像数据库vid这个参数不支持参数化，如果不涉及注入问题，可以使用`${p}`代替

**Comment by sakuraemiya** [comment]
> 看着像数据库vid这个参数不支持参数化，如果不涉及注入问题，可以使用`${p}`代替

还是不行，go from ${cityVid} over cityHaveOrder yield id($$) as vid
05:55:17:变量未定义(VAR_NOT_DEFINED):cityVid 位于2行
org.nebula.contrib.ngbatis.exception.QueryException: 数据查询失败： 数据查询失败SyntaxError: syntax error near ` fro'

**Comment by sakuraemiya** [comment]
> 看着像数据库vid这个参数不支持参数化，如果不涉及注入问题，可以使用`${p}`代替

还是不行  go from ${cityVid} over cityHaveOrder yield id($$) as vid
变量未定义(VAR_NOT_DEFINED):cityVid 位于2行
org.nebula.contrib.ngbatis.exception.QueryException: 数据查询失败： 数据查询失败SyntaxError: syntax error near ` fro'

**Comment by CorvusYe** [comment]
mapper接口的方法签名的参数有`@Param("cityVid")`吗

**Comment by sakuraemiya** [comment]
> mapper接口的方法签名的参数有`@Param("cityVid")`吗

有的

**Comment by sakuraemiya** [comment]
(@Param("cityVid") String cityVid)

**Comment by CorvusYe** [comment]
这个是字符串类型，需要有引号包裹，可以试试`'${cityVid}'`或者 `${ng.valueFmt(cityVid)}`

**Comment by sakuraemiya** [comment]
> 这个是字符串类型，需要有引号包裹，可以试试`'${cityVid}'`或者 `${ng.valueFmt(cityVid)}`

不行 还是一样的报错

**Comment by sakuraemiya** [comment]
> 这个是字符串类型，需要有引号包裹，可以试试`'${cityVid}'`或者 `${ng.valueFmt(cityVid)}`

我是用ng.valueFmt 在xml文件里面ng直接标红

**Comment by CorvusYe** [comment]
哈喽哈喽，方便提供一下报错截图吗

**Comment by sakuraemiya** [comment]
> 哈喽哈喽，方便提供一下报错截图吗

![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/0abb2747-f34b-43f2-89d2-a8895c2fe0f0)

**Comment by CorvusYe** [comment]
可能导致的问题有 `@Param` 使用的包与案例中的不一致，是java.p....的这个包，这种可能性会导致变量重命名失败，从而这个参数还是使用了默认的参数名 p0

**Comment by sakuraemiya** [comment]
> 可能导致的问题有 `@Param` 使用的包与案例中的不一致，是java.p....的这个包，这种可能性会导致变量重命名失败，从而这个参数还是使用了默认的参数名 p0

![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/a04543d1-6c55-491a-a3c3-0efa1fbb25fa)
我使用的apach的包，请问案例中的是包全称是什么

**Comment by CorvusYe** [comment]
不好意思，刚刚说错了，是spring的包，全限定名是  
 ​org​.​springframework​.​data​.​repository​.​query​.​Param​

**Comment by sakuraemiya** [comment]
> 不好意思，刚刚说错了，是spring的包，全限定名是​org​.​springframework​.​data​.​repository​.​query​.​Param​

好的 查询正常了
