### ISSUE TITLE
error on dependency version

### ISSUE THREAD

**Issue by sakuraemiya** [nebula-contrib/ngbatis#252]
你好，
![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/ca394117-719c-4f6a-a6e5-2ca4d6034007)
这个包可能存在漏洞，所以把版本升级了，升级3.15.7.RELEASE，执行后报错，
![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/dc556611-0dd6-4b1e-bdd4-ce0b65242288)
发现高版本的这个方法入参从String改成了Object
![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/84c300ab-bc71-4866-ae83-068c4f4528cd)
请问有没有什么方法在不降低版本的情况下解决这个问题

**Comment by CorvusYe** [comment]
你好，如果高版本是Object类型的参数，应该是不影响String类型的传入才对。编译没有问题，只是运行时的报错吗？如果是运行时报错，可以试试自己实现一个TextRender，然后用`@Primary`来提高组件优先级

**Comment by sakuraemiya** [comment]
> 你好，如果高版本是Object类型的参数，应该是不影响String类型的传入才对。编译没有问题，只是运行时的报错吗？如果是运行时报错，可以试试自己实现一个TextRender，然后用`@Primary`来提高组件优先级

运行时报错，是很奇怪，我试试自己重写一个TextRender

**Comment by CorvusYe** [comment]
> 解决了 但是很奇怪啊 我就只是把`BeetlTextRender`这个方法复制了一遍就可以了 也没改动其他东西

那现在如果把复制的再去掉行不行？不然这个事显得会有点诡异

**Comment by sakuraemiya** [comment]
> > 解决了 但是很奇怪啊 我就只是把`BeetlTextRender`这个方法复制了一遍就可以了 也没改动其他东西
> 
> 那现在如果把复制的再去掉行不行？不然这个事显得会有点诡异

不行 去掉就报错  不知道时啥情况

**Comment by CorvusYe** [comment]
> > > 解决了 但是很奇怪啊 我就只是把`BeetlTextRender`这个方法复制了一遍就可以了 也没改动其他东西
> > 
> > 那现在如果把复制的再去掉行不行？不然这个事显得会有点诡异
> 
> 不行 去掉就报错  不知道时啥情况

JDK的版本是？

**Comment by sakuraemiya** [comment]
> > > > 解决了 但是很奇怪啊 我就只是把`BeetlTextRender`这个方法复制了一遍就可以了 也没改动其他东西
> > > 
> > > 
> > > 那现在如果把复制的再去掉行不行？不然这个事显得会有点诡异
> > 
> > 
> > 不行 去掉就报错  不知道时啥情况
> 
> JDK的版本是？

jdk8

**Comment by CorvusYe** [comment]
OK，那将就着先用着哈，晚点我手边有电脑了再试着换到beetl3.15的看看能不能重现

**Comment by sakuraemiya** [comment]
> OK，那将就着先用着哈，晚点我手边有电脑了再试着换到beetl3.15的看看能不能重现

好的
