### ISSUE TITLE
NebulaDaoBasic是否可以实现一个listEndNodes方法

### ISSUE THREAD

**Issue by qiuchen001** [nebula-contrib/ngbatis#261]
目前，NebulaDaoBasic中有个istStartNodes方法，在查询时很方便
![16e16cd2fc2bb97e4c4c51e19770777](https://github.com/nebula-contrib/ngbatis/assets/139746392/fbd43ab1-9eb5-4467-af0b-a1923af26c65)

listEndNodes的功能也很常用，是否也可以实现一个listEndNodes方法呢

**Comment by shbone** [comment]
Maybe this function is useful. And I will have a try

**Comment by CorvusYe** [comment]
@shbone 
I am looking forward to this new feature and glad that you are interested in it.
Just do it !

**Comment by CorvusYe** [comment]
@qiuchen001 
这个接口已经完成支持，我就先关闭了哈。有需要可以再开。
最早支持的版本是[v1.2.0](https://github.com/nebula-contrib/ngbatis/releases/tag/v1.2.0)

感谢来自 @knqiufan 的PR
