### ISSUE TITLE
consider changing the rules of style_checks?

### ISSUE THREAD

**Issue by CorvusYe** [nebula-contrib/ngbatis#27]
Under this configuration, many rules are anti habit, for example:
- The field ''{0}'' must be declared final.
    > - When we see the source code in spring or Java, we rarely see it in this way, 
    > and it is not used in normal development. 
    > - It is a good thing to have specifications, 
    > but perhaps too anti customary rules will not be conducive to the participation of developers.
- First sentence should end with a period. 
    > This rule only accepts `.`, with out `。` and newline
- ...

**Comment by Nicole00** [comment]
Google style is the most widely used code style, but Chinese code style maybe a little different from it, such as indentation, which can be adjusted according to the `common` habits.

**Comment by Nicole00** [comment]
I have added the google code style configure xml in pr https://github.com/nebula-contrib/ngbatis/pull/23, (have changed the tab size to 4 from 2) .  please force merge and change it in another pr.

**Comment by wey-gu** [comment]
We could gradually Add English Javadoc in front of the Chinese ones(or replace them?)

**Comment by CorvusYe** [comment]
> We could gradually Add English Javadoc in front of the Chinese ones(or replace them?)

I think the domestic market should be easier to promote than the international market. It is necessary to keep the Chinese documents on the basis of adding i18n.
After all, there are still some programmers who are hard to accept English docs.(Take me for example.)

**Comment by wey-gu** [comment]
> > We could gradually Add English Javadoc in front of the Chinese ones(or replace them?)
> 
> I think the domestic market should be easier to promote than the international market. It is necessary to keep the Chinese documents on the basis of adding i18n. After all, there are still some programmers who are hard to accept English docs.(Take me for example.)

Yes, agreed, we should maintain both lang :)
