### ISSUE TITLE
 ResultSet error: SyntaxError: syntax error near `  go '

### ISSUE THREAD

**Issue by sakuraemiya** [nebula-contrib/ngbatis#286]
你好，我在mapper层传入一个double类型的数据
![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/338f5bb8-ef67-453f-93a9-6a1c3324d0f2)
在xml中这么写
![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/2a98b312-34aa-4f4e-a827-33b4df4974c0)
他会报错
![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/c0728426-d0b8-4208-8a69-bd8a4c2e3eb7)
这是什么问题，直接写ngql执行没有问题，但是在代码里就会报错

**Comment by CorvusYe** [comment]
这边如果是类似于preparedStatement，直接用 {weight}，不需要井号哈～

**Comment by sakuraemiya** [comment]
> 这边如果是类似于preparedStatement，直接用 {weight}，不需要井号哈～

不行欸
![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/6df68329-bdb1-48b9-baa9-f7d7f3b930f3)
![image](https://github.com/nebula-contrib/ngbatis/assets/42309426/0518df46-81ff-4831-8bb0-3351a1083976)

**Comment by CorvusYe** [comment]
这个位置不支持参数化，可以试试 ${weight}

**Comment by sakuraemiya** [comment]
> 这个位置不支持参数化，可以试试 ${weight}

好的 可以了

**Comment by sakuraemiya** [comment]
> 这个位置不支持参数化，可以试试 ${weight}

我其他的参数就可以使用#{}来传入，只有这个参数不行，是有什么区别嘛

**Comment by CorvusYe** [comment]
其他的是这个格式吗？ `“#{}”` ，印象中不支持使用 # 来做参数占位来着

**Comment by sakuraemiya** [comment]
> 其他的是这个格式吗？ `“#{}”` ，印象中不支持使用 # 来做参数占位来着

没事了 看错了 其他参使也是${}处理的 太久没写记混了

**Comment by sakuraemiya** [comment]
1
