### ISSUE TITLE
publishing to maven

### ISSUE THREAD

**Issue by wey-gu** [nebula-contrib/ngbatis#3]

**Comment by CorvusYe** [comment]
This is my first time to publish a project to Maven

I didn't understand many details, so I registered my account and tried to publish it.

If I want to publish to nebula-contrib Maven REPO, maybe I need an account.

Thanks a lot.

**Comment by CorvusYe** [comment]
Dear @wey-gu :

This is my first time to publish a project to Maven

I didn't understand many details, so I registered my account and tried to publish it.

If I want to publish to nebula-contrib Maven REPO, maybe I need an account.

Thanks a lot.

**Comment by wey-gu** [comment]
> Dear @wey-gu :
> 
> This is my first time to publish a project to Maven
> 
> I didn't understand many details, so I registered my account and tried to publish it.
> 
> If I want to publish to nebula-contrib Maven REPO, maybe I need an account.
> 
> Thanks a lot.

Dear @CorvusYe 

You could refer to https://github.com/nebula-contrib/nebula-jdbc/blob/master/.github/workflows/maven-publish.yml , the secret env vars are already set, before that, I will help create a maven repo, I will let you know when it's finished.

**Comment by wey-gu** [comment]
@CorvusYe , could you help check this? https://github.com/nebula-contrib/ngbatis/pull/6

**Comment by CorvusYe** [comment]
> @CorvusYe , could you help check this? #6

@wey-gu I've merge the branch into master.

What I'm not sure about is whether the workflow will be automatically triggered and published to maven when the new version is released.

Do I need to do some configuration ? Because it was deploy failed at local mvn command.

**Comment by wey-gu** [comment]
@CorvusYe thanks!
I could see it's uploaded with the snapshot release.

here: https://s01.oss.sonatype.org/content/repositories/snapshots/org/nebula-contrib/ngbatis/
and: https://github.com/nebula-contrib/ngbatis/runs/7392649702?check_suite_focus=true

Maybe we could make a final release with more polishing work done then :).

**Comment by CorvusYe** [comment]
@wey-gu 
Yes, there are some things to do, such as using connection pool and extending more methods in NebulaDaoBasic, and etc.
