### ISSUE TITLE
NebulaDaoBasic 中的 insert，是否考虑支持没有 if not exists 的语句？

### ISSUE THREAD

**Issue by swiftlei** [nebula-contrib/ngbatis#324]
当前 NebulaDaoBasic 中的 insert* 系列方法，具体的插入语句中都使用了 insert vertext if not exists 
但很多场景中，insert vertex 但没有 if not exists 子句的用法是有价值的，比如多次高效地覆盖同一个点或边（使用upsert语句效率较低）
是否考虑增加类似 insertOrReplace 这样的方法或者在insert方法中引入 boolean 开关变量来由用户决定是否需要使用 if not exists 条件？

还有一个原因，就是此 mapper 中，对于 insertEdge* 系列方法就没有使用 if not exists 子句，与插入点的逻辑也不太一致

**Comment by CorvusYe** [comment]
之前也有开发者提过，后来遗漏了。
下个版本体现～
