### ISSUE TITLE
springboot 2.7 + jdk17 的环境下，会出现java.base中的内部API未导出错误

### ISSUE THREAD

**Issue by swiftlei** [nebula-contrib/ngbatis#327]
在 springboot 2.7 + jdk17 的环境下，使用 ngbatis 1.3.0版本配置好项目，启动时会出现：
cannot access class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl (in module java.base) because module java.base does not export sun.reflect.generics.reflectiveObjects to unnamed module ...
at org.nebula.contrib.ngbatis.utils.ReflectUtil.typeToClass
 的错误

请问:是不是ngbatis中使用了jdk 8 以后的版本中默认不支持的内部API?  除了添加 --add-exports 的JVM参数，这种情况是否有什么好的解决方案？

**Comment by CorvusYe** [comment]
项目中是否支持允许使用springboot 3.x？
允许的话，可以试试1.3.0-jdk17，整体适配度会更强一些。

**Comment by swiftlei** [comment]
> 项目中是否支持允许使用springboot 3.x？ 允许的话，可以试试1.3.0-jdk17，整体适配度会更强一些。

确实不方便切换springboot 到 3.x，也不方便降级jdk到8。请问是否还有其他优雅一些的解决方案？

**Comment by CorvusYe** [comment]
目前除了加虚拟机参数，还可以迁1.3.0的tag源码做修改，然后编译一个适配版本。
引用内部具体实现的做法应该会在下个版本看看能不能改掉。毕竟不仅仅不能适配17，openjdk上使用也存在一定问题。
