### ISSUE TITLE
method "selectBySelective" with primary key

### ISSUE THREAD

**Issue by soul-gin** [nebula-contrib/ngbatis#35]
I think this method is better to eliminate the primary key.(@var kv = ng.kv( ng_args[0], '', false, true, false ); -> @var kv = ng.kv( ng_args[0], '', true, true, false );)

When primary key name field is included, it cannot query the results correctly
USE test; MATCH (n:`person`) WHERE n.`person`.age == 18 and n.`person`.name == '赵小洋' RETURN n LIMIT 4000;
without primary key:
USE test; MATCH (n:`person`) WHERE n.`person`.age == 18  RETURN n LIMIT 4000;

ps: I'm using version nebula-graph-3.2.0.el7.x86_64.rpm

**Comment by CorvusYe** [comment]
You are rignt. It's really a bug. Thanks for your issue. 
What do you think of the following gql:  
```cql
USE test; 
MATCH (n:person) 
WHERE id(n) == '赵小洋' 
   AND n.person.age == 18 
RETURN n 
LIMIT 4000;
```
Is it more in line with our expectations when primary key name field is included?

**Comment by soul-gin** [comment]
Thank you for your answer.
"id(n) == '赵小洋' " is indeed a better option.
