### ISSUE TITLE
About publishing a new version

### ISSUE THREAD

**Issue by CorvusYe** [nebula-contrib/ngbatis#37]
as title

**Comment by wey-gu** [comment]
I'm good to do so, we may need to have a process on the SIG of ngbatis(like @CorvusYe could start a new version proposal ) :-D

**Comment by wey-gu** [comment]
cc @Nicole00

**Comment by CorvusYe** [comment]
[1.1.0-rc](https://github.com/nebula-contrib/ngbatis/releases/tag/1.1.0-rc)
