### ISSUE TITLE
I want to know why the contributor information is not accurate

### ISSUE THREAD

**Issue by CorvusYe** [nebula-contrib/ngbatis#42]
When we see this file [ReflectUtil](https://github.com/nebula-contrib/ngbatis/blob/master/src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java), 
we can only find 1 contributor, but we find the commit log by @soul-gin meanwhile. 
Shouldn't 2 contributors be displayed?
I am not familiar with this aspect. What's wrong. @wey-gu 

![image](https://user-images.githubusercontent.com/15630211/189509371-00c5538d-e2c8-419a-bb78-4f4b67289ceb.png)

**Comment by wey-gu** [comment]
This could be caused by:
1. it's eventual consistency, not synced in real-time?
2.  @soul-gin 's privacy setting lead this?(i.e. email privacy etc.)
