### ISSUE TITLE
Controller层插入关系

### ISSUE THREAD

**Issue by DawnZzzzz** [nebula-contrib/ngbatis#49]
您好，请问
1、想创建两个已有点之间的关系该如何写呢
 @RequestMapping("/addr/{person1}/{like}/{person2}")
    public String addRelation(@PathVariable(name = "person1") String name1,@PathVariable(name = "like") String like,@PathVariable(name = "person1") String name2){
        Person person1 = new Person();
        person1.setName(name1);
        Person person2 = new Person();
        person1.setName(name2);
        Like like1= new Like(0.9999);
        personDao.insertEdge(person1,like,person2);
        return "success";

2、Likeness只能是Double类型吗？想创建“包含”、“属于”这样的关系
org.nebula.contrib.ngbatis.exception.QueryException:  数据查询失败Storage Error: The data type does not meet the requirements. Use the correct type of data.

3、添加点这样写是否科学
@RequestMapping("/add/{name}/{age}")
    public String addPerson(@PathVariable(name = "name") String name,@PathVariable(name = "age") Integer age){
        Person person = new Person();
        person.setName(name);
        person.setAge(age);
        personDao.insert(person);
        System.out.println(person + "添加成功!");
        return "success";
    }

**Comment by CorvusYe** [comment]
1. 如果是直接用的 NebulaDaoBasic，【1、】中的写法可以写入数据库给，但要注意数据库的 属性类型 是否与实体类中的属性类型是否一致、注意数据库主键类型与实体类的 @Id 的属性类型是否一致。

2. 如果想创建其他的关系，可以不使用 Like 这个类来做关系，在数据库建一个对应的 edge, 然后参照 Like 建一个其他名字的类，并声明好@Table 就可以，

3. 这样添加点，从效果上可以实现，但从使用习惯上会显得比较别扭。参数建已通过 data 的方式传递，通过 url 传递会显得局限，而且没办法用上 mvc 的参数封装，需要自己调很多次 set.
    ```java
      @RequestMapping("/add")
      public String addPerson( Person person ) {
         personDao.insert( person );
      }
    ```
    ```js
    // 不确定你前端用的是什么异步请求方案，以下只作为伪代码
    ajax({
       url: 'add',
       data: {
          name: '',
          age: 18
       }
    })
    ```

**Comment by DawnZzzzz** [comment]
老师，【1、】的方法就是不能插入关系。我改成这样了不能插入person1和person2的关系，反而插入了一个新的点，并生成了新的点的person2的关系是怎么回事呢
> 
@RequestMapping("/addr/{name1}/{name2}")
    public String addRelation(@PathVariable(name = "name1") String name1,@PathVariable(name = "name2") String name2){
        Person person1 = new Person();
        person1.setName(name1);
        personDao.insertSelective( person1 );
        Person person2 = new Person();
        person1.setName(name2);
        personDao.insertSelective( person2 );
        Like like1= new Like();
        personDao.insertEdge(person1,like1,person2);
        System.out.println(like1 + "添加成功!");
        return "success";
    }
> 
![QQ截图20220922122052](https://user-images.githubusercontent.com/87481351/191657866-49470bab-cb22-4f89-80ce-cbc66e7c217a.png)
![QQ截图20220922122109](https://user-images.githubusercontent.com/87481351/191657875-05ac3236-8ff3-4014-98a2-97978bd3abe1.png)

我就是用的ngbatis里面自带的demo，我希望大规模数据在studio通过csv添加，零星的数据通过发布成服务用url进行crud，实现远程访问，这样做可以吗？老师对实现我这种需求什么建议吗，您提的第三点建议有点看不懂

**Comment by CorvusYe** [comment]
> 我改成这样了不能插入person1和person2的关系，反而插入了一个新的点，并生成了新的点的person2的关系是怎么回事呢

生成的结果跟代码表达的意思是一致的。
```java
@RequestMapping("/addr/{name1}/{name2}")
public String addRelation(@PathVariable(name = "name1") String name1,@PathVariable(name = "name2") String name2){
  Person person1 = new Person();
  person1.setName(name1);
  personDao.insertSelective( person1 );   // 插入了 person1

  Person person2 = new Person();
  person1.setName(name2);
  personDao.insertSelective( person2 );  // 插入了 person2

  Like like1= new Like();
  personDao.insertEdge(person1,like1,person2);  // 插入了 person1 跟 person2 的关系

  System.out.println(like1 + "添加成功!");
  return "success";
}
```

**Comment by CorvusYe** [comment]
关于第三点建议

还以为你有对应的页面来填写表单。
如果是通过 url 来传递参数的话，能传输的量会比较局限。

在不写html页面的情况下，可以使用 Apifox 或者 Postman 来代替 url 的请求，
这样能传递的参数可能更丰富。毕竟需要保存的可能不仅仅是两个名字。

**Comment by DawnZzzzz** [comment]
嗯嗯谢谢老师！问题解决了，我继续把我做的这个完善一下
