### ISSUE TITLE
space不起作用

### ISSUE THREAD

**Issue by hejiahuichengxuyuan** [nebula-contrib/ngbatis#50]
- 我的语句是这样的 , 但是我发现查询语句不起作用，走的space还是我配置在yml中的sapce
```
<select id="relationshipExpansionSubGraph" space="subgraph" resultType="com.vesoft.nebula.client.graph.data.ResultSet">
    GET SUBGRAPH WITH PROP ${stepNum} STEPS FROM "${nodeId}"
    @if (isNotEmpty(relationshipList)) {
        BOTH
        @for ( item in relationshipList ) {
            ${item} ${ itemLP.last ? '' : ',' }
        @}
    @}
    YIELD VERTICES AS nodes, EDGES AS relationships
    </select>
```

- 日志
- nGql：USE test;
		GET SUBGRAPH WITH PROP 2 STEPS FROM "player101"
    YIELD VERTICES AS nodes, EDGES AS relationships 
	 - params: {spaceName=subgraph, relationshipList=null, stepNum=2, nodeId=player101}
	 - result：ColumnName: [nodes, relationships], Rows: [[("player101" )],[]]

**Comment by hejiahuichengxuyuan** [comment]
原始语句 `<select id="relationshipExpansionSubGraph" space="subgraph"  resultType="com.vesoft.nebula.client.graph.data.ResultSet">
    `

**Comment by CorvusYe** [comment]
方便在下面的方法内断点看看入参吗？
> 所在类: MapperProxy
```java
  public static String getSpace(ClassModel cm, MethodModel mm) {
    return mm != null && mm.getSpace() != null ? mm.getSpace()
      : cm != null && cm.getSpace() != null ? cm.getSpace()
      : ENV.getSpace();
  }
```

**Comment by hejiahuichengxuyuan** [comment]
是我的问题，idea缓存还是原来的beta版本。我重刷缓存就好了
请问可以动态的设置spaceName吗？相当于 space="${spaceName}" 这样的

**Comment by CorvusYe** [comment]
> 请问可以动态的设置space吗？相当于 space="${spaceName}" 这样的
是调用同一个 select 指定不同的 space 吗？
如果是 这个意思，你的 relationshipExpansionSubGraph 方法需要把 spaceName 做为方法参数传进来
然后在 xml 中使用，首行加一句：use `${spaceName}`;

但是这种方式可能会运行两次 use 语句，虽然会有一定的额外开销，但也是可以实现。
目前框架暂不支持根据实体自动获取 spaceName

**Comment by hejiahuichengxuyuan** [comment]
好的

**Comment by CorvusYe** [comment]
这边看到 relationshipExpansionSubGraph 使用 ResultSet 返回
如果对项目内特定的数据结构做处理又想把这个处理方式固化下来，可以声明一个类继承 `AbstractResultHandler<T, Z>`。
只要 T,Z 跟现有的类型不冲突，并给上@Component就行。

**Comment by CorvusYe** [comment]
> 请问可以动态的设置space吗？相当于 space="${spaceName}" 这样的

仔细想了下，现在的版本如果你想在运行时在同一个方法中使用不同的 space，又不想在方法上加 spaceName 的参数，可以使用自定义函数，从已有的入参中获取

新加自定义函数的方法：
1. 在 resources 下建一个 beetl.properties 文件
2. 文件内容为：FN.your.fnName =org.nebula.contrib.ngbatis.binding.beetl.functions.KvFn，把这个类换成自建的类
3. 自建的类继承 AbstractFunction<A, B, C, D, E, F>
  > 泛型为调用这个方法入参的类型
4. 如果只有一个入参，则
    ```java
    public Object call(A param) { // A 需要写成实际的类型
        // 从入参中获取到 spaceName
        return null;
    }
    ```
6. 在xml中使用：@your.fnName( 参数a )

**Comment by hejiahuichengxuyuan** [comment]
```
public class DynamicSpace extends AbstractFunction<Object, Void, Void, Void, Void, Void> {


    public DynamicSpace() {
    }

    public String call(String param) {
        return param;
    }
}
```

`<select id="relationshipExpansionSubGraph" space="@my.fnName(${spaceName})" resultType="com.vesoft.nebula.client.graph.data.ResultSet">`

- 是这样吗？

**Comment by CorvusYe** [comment]
不是的，比如说：
- dao方法
  ```java
  ResultSet relationshipExpansionSubGraph( @Param("paramListWithSpace") List<Map<String, ?>> paramWithSpace );
  ```

- beetl.properties 追加一行
  ```properties
  # 之前的就不写了

  # 声明你所需的函数
  FN.my.fnName =your.domain.project.**.DynamicSpace
  ```

- 方法体
```java
@Component
public class DynamicSpace extends AbstractFunction<Map<String, ?>, Void, Void, Void, Void, Void> {

    public DynamicSpace() {
    }

    public String call(Map<String, ?> paramWithSpace ) {
        // getter 表示：通过 paramWithSpace  获取到 space，需要自己根据情况实现
        String spaceName =  paramWithSpace.get( "spaceNameKey" );
        return spaceName;
    }
}
```

```xml
<select id="relationshipExpansionSubGraph" resultType="com.vesoft.nebula.client.graph.data.ResultSet">
    
    @for ( item in paramListWithSpace) {
        USE @my.fnName( paramWithSpace );

        <!-- 遍写其他 gql -->

    @}
</select>
```

**Comment by hejiahuichengxuyuan** [comment]
感谢大佬提供示例和思路！这对我很有帮助

**Comment by CorvusYe** [comment]
上面的例子不是很恰当

多次切换 space 的用法，更多的适用于 insert 或者 update 这样不需要返回值的操作。

但对 select 的操作，也相当于一次动态space。 因为 nebula 本身不支持多返回，只会返回最后一个 return 或 yeild

**Comment by hejiahuichengxuyuan** [comment]
> 这边看到 relationshipExpansionSubGraph 使用 ResultSet 返回 如果对项目内特定的数据结构做处理又想把这个处理方式固化下来，可以声明一个类继承 `AbstractResultHandler<T, Z>`。 只要 T,Z 跟现有的类型不冲突，并给上@ Component就行。
> 
> * T 是 接口的返回值类型（不包括泛型）
> * Z 是 xml 中声明的 resultType（如果 resultType 与接口返回值类型一致，xml 中可以不用写）

想询问下对于这种返回的结构，我应该用什么 resultType去接受比较好？
![image](https://user-images.githubusercontent.com/43517569/191680164-4b56b909-14b6-4f9b-ae9c-aa760733e46a.png)

**Comment by CorvusYe** [comment]
你这边是想获取类似于
player101 - follow -> player102
这样的关系是吗

**Comment by hejiahuichengxuyuan** [comment]
这个getSubgraph是 nodes:List edge:List，按照ResultSet的类型的话我是这样做才能取到值
```
for (int i = 0; i < resultSet.rowsSize(); i++) {

            ResultSet.Record record = resultSet.rowValues(i);
            ArrayList<ValueWrapper> nodes = record.get("nodes").asList();
            ArrayList<ValueWrapper> relationships = record.get("relationships").asList();

            System.out.println("nodes---------------------------");
            for (ValueWrapper node : nodes) {
                Node n = node.asNode();
                System.out.println("n.tagNames() = " + n.tagNames());
                for (String tagName : n.tagNames()) {
                    System.out.println("n.properties(tagName) = " + n.properties(tagName));
                }
            }

            System.out.println("edges---------------------------");
            for (ValueWrapper relationship : relationships) {
                Relationship r = relationship.asRelationship();
                System.out.println("r.properties() = " + r.properties());
            }
        }
```
- 我是想有没有其他的类型接受可以更好的直接解析出来

**Comment by hejiahuichengxuyuan** [comment]
如果不知道字段的是什么类型的话，每次都还要 nodes.isList 和 relationship.isList 的判断，还要 as的转换，感觉很不方便，如果可以做到已经转好类型就好了

**Comment by CorvusYe** [comment]
> 如果不知道字段的是什么类型的话，每次都还要 nodes.isList 和 relationship.isList 的判断，还要 as的转换，感觉很不方便，如果可以做到已经转好类型就好了

关于这个问题，你可以试试 ResultSetUtil.getValue

**Comment by hejiahuichengxuyuan** [comment]
我自己也写了个转换类，你的工具类写的比我好哈哈我还是用你的

**Comment by CorvusYe** [comment]
> * 我是想有没有其他的类型接受可以更好的直接解析出来


关于这个问题，你可以试试下面的数据结构，自己新建一个类：
```java
@Data
public class SubgraphResult {
    private List<Player> nodes; // 与 xml 变量名相对应
    private List<Relationship> relationships; // 与 xml 变量名相对应
}
```

resultType 使用  SubgraphResult

**Comment by hejiahuichengxuyuan** [comment]
我是不知道是用哪个实体去接受的所以还是得用 List<ValueWrapper>，因为我的业务都是动态查询，anyway，Thanks♪(･ω･)ﾉ

**Comment by CorvusYe** [comment]
如果都是动态的，直接返回 ResultSet 确实是个比较好的选择
