### ISSUE TITLE
映射文件解析异常：class java.lang.String 必须有一个属性用 @Id 注解。（javax.persistence.Id）

### ISSUE THREAD

**Issue by DawnZzzzz** [nebula-contrib/ngbatis#51]
`@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "node")
public class Node {
    @Id
    private String id;
    private String name;

}
`

`    @RequestMapping("/addr/{name1}/{name2}")
    public String addRelation(@PathVariable(name = "name1") String name1,@PathVariable(name = "name2") String name2){
        Node node1 = new Node();
        node1.setName(name1);
        nodeDao.insertSelective( node1 );
        Node node2 = new Node();
        node2.setName(name2);
        nodeDao.insertSelective( node2 );
        Relation relation=new Relation();
        nodeDao.insertEdge(name1,relation,name2);
        System.out.println(relation + "添加成功!");
        return "success";
    }`
老师好，一直报这个问题，设置成按id添加关系也不行。
另外想问一下vid和id属性绑定的，可不可以设置成自增id呢，这样只用添加name就行

**Comment by CorvusYe** [comment]
### 关于插入关系，insertEdge 入参使用 实体对象，例子如下：
```diff
@RequestMapping("/addr/{name1}/{name2}") 
public String addRelation(@PathVariable(name = "name1") String name1,@PathVariable(name = "name2") String name2) { 
    Node node1 = new Node(); 
    node1.setName(name1); 
    nodeDao.insertSelective( node1 ); 
    Node node2 = new Node(); 
    node2.setName(name2); 
    nodeDao.insertSelective( node2 ); 
    Relation relation=new Relation(); 
-    nodeDao.insertEdge(name1,relation,name2); 
+    nodeDao.insertEdge(node1, relation, node2); 
    System.out.println(relation + "添加成功!"); 
    return "success"; 
}
```

### 关于自增id，可能自己声明主键生成器
可以参考以下的配置：【[项目引入与配置](https://corvusye.gitee.io/ngbatis-docs/#/?path=quick-start&file=install)】，关于主键配置在该页最下面。

**Comment by DawnZzzzz** [comment]
谢谢老师！学习您的文档
