### ISSUE TITLE
ngbatis中通过发送post请求提供tag的非主键属性，为两个已知点添加edge

### ISSUE THREAD

**Issue by DawnZzzzz** [nebula-contrib/ngbatis#57]
老师好，因为id设置的是随机值，所以想通过分别提供两个点的name属性为两个点添加edge，基类中似乎只能通过主键id添加，mapper中只有select没有insert。请问该如何操作呢？已经创建index。 感谢！

controller层
```java
    @PostMapping("/add/relation")
    public String addRelation(Relation relation){
        Relation relation1= new Relation();
        //personDao.insertEdge(person1,relation1,person2);
        System.out.println(relation1 + "添加成功!");
        return "success";
    }
```

pojo层
```java
public class Person {

    @Id
    private String id=java.util.UUID.randomUUID().toString();
    private String meta_type;
    private String name;
    private String company;
    private String post;
    private String gender;
    private String birthday;
    private String title;
    private String state;

}
```

```java
public class Relation {
    private String name1;
    private String relation;
    private String name2;
}
```
HTML
<body>
<form th:action="@{/add/relation}" method="post">
    <table>
        <tr>
            <th colspan="2">add relation</th>
        </tr>
        <tr>
            <td>名称1</td>
            <td>
                <input type="text" name="name1">
            </td>
        </tr>
        <tr>
            <td>关系</td>
            <td>
                <input type="text" name="relation">
            </td>
        </tr>
        <tr>
            <td>名称2</td>
            <td>
                <input type="text" name="name2">
            </td>
        </tr>
    </table>
</form>
</body>

**Comment by CorvusYe** [comment]
ngbatis插入关系目前仅支持通过id插入，看看能不能通过name先把两个节点找出来？

**Comment by DawnZzzzz** [comment]
上传的名称1是person的name属性（主键），如何通过主键确定点赋值给person1?，再添加person1和person2之间的关系？求助，想了一下午了，selectById只能查找点啊
`
@PostMapping("/add/relation")
    public String addRelation(Person person1,Relation relation,Person person2){

        person1 = personDao.selectById(relation.getName1());
        personDao.insertEdge(person1,relation,person2);
        System.out.println(relation + "添加成功!");
        return "success";
    }
`

**Comment by CorvusYe** [comment]
如果post请求addRelation方法时，person1有name属性，person2也有name属性，并且name有`@Id`注解，那么不用再selectById了，直接执行你写的那行insertEdge就可以了，这个方法会通过两个name建立两个点的关系

**Comment by DawnZzzzz** [comment]
`
@PostMapping("/add/relation")
    public String addRelation(String name1,Relation relation,String name2){
        Person person1 = personDao.selectById(name1);
        Person person2 = personDao.selectById(name2);
        personDao.insertEdge(person1,relation,person2);
        System.out.println(relation + "添加成功!");
        return "success";
    }
`
老师，写成这样可以了，但是只能添加同一个标签的关系，如果要添加不同标签之间（如person和company），不是添加关系都要反复写很多post请求？

`
@PostMapping("/add/relation1")
    public String addRelation1(String name1,Relation relation,String name2){
        Person person1 = personDao.selectById(name1);
        Company company1 = companyDao.selectById(name2);
        personDao.insertEdge(person1,relation,company1);
        System.out.println(relation + "添加成功!");
        return "success";
    }

`

**Comment by CorvusYe** [comment]
```java
    Person person1 = new Person();
    person1.setName(name1);
    Person personDb1 = personDao.selectSelective(person1);
```
这个时候，personDb1就有id属性了
同样的方式获得 peraonDb2
然后insertEdge就行了。

**Comment by CorvusYe** [comment]
抱歉，上面那个看错了。还以为是name不是主键的情况。
如果是很多种关系，可以把关系跟对应起止节点的类型传进来，获取不同tag的节点，再插入关系~

**Comment by DawnZzzzz** [comment]
是的老师，但是这样是新建点而且只有name属性。我想添加已有点间的关系，且这个点有多个属性

**Comment by CorvusYe** [comment]
如果想实现动态的，可以在 PersonDao.xml 下(或另建一个dao)，建两个 insert 标签，一个用来动态节点，一个用来建立关系。

这样，可以通过 post 的参数指定要建立的要创建的节点数据与tag，要建立什么样的关系也是一样。

可以参考 NebulaDaoBasic.xml id="insert" 的标签

**Comment by CorvusYe** [comment]
这个 issue 或许对你有帮助：https://github.com/nebula-contrib/ngbatis/issues/14

**Comment by DawnZzzzz** [comment]
明白了，非常感谢老师那么晚解答！我明天试试insert标签

**Comment by CorvusYe** [comment]
不客气。有问题可以及时提，我看到了就会回，一般都会开邮件。
另外，如果评论中想做代码高亮，可以用以下的格式：
\`\`\`java
    // 这里放 java 代码
\`\`\`
如果是，其他代码比如说 xml 把 java 换成 xml 就行。

**Comment by DawnZzzzz** [comment]
路径查询,输入起始\结束点name，请问这样写为什么不对呢
```
<select id="selectPath" resultType="edu.swjtu.vge.cz.knowledgebacemanager.pojo.NRN2">
        <!--MATCH p=(n: person{name:${name1}})-[r: relation]->(n2: person{name:${name2}})-->
        MATCH p=(n: person)-[]->(n2: person)
        WHERE id(n) = '${name1}',id(n2) = '${name2}'
        RETURN n, r, n2
        LIMIT 1
    </select>
```

```
@PostMapping("/match/p")
    public String matchP( @Param("name1") String name1,@Param("name1") String name2){
        List<NRN2> paths = personDao.selectPath(name1,name2);
        System.out.println(JSON.toJSONString(paths) + "添加成功!");
        return "success";
    }
```

```
public interface PersonDao extends NebulaDaoBasic<Person, String> {
    
    List<NRN2> selectPath(@Param("name1") String name1,@Param("name2") String name2);}
```

**Comment by CorvusYe** [comment]
```diff
<select id="selectPath" resultType="edu.swjtu.vge.cz.knowledgebacemanager.pojo.NRN2">
    <!--MATCH p=(n: person{name:${name1}})-[r: relation]->(n2: person{name:${name2}})-->
-     MATCH p=(n: person)-[]->(n2: person)
-     WHERE id(n) = '${name1}',id(n2) = '${name2}'
+    MATCH p=(n: person)-[r]->(n2: person)
+    WHERE id(n) == '${name1}',id(n2) == '${name2}'
    RETURN n, r, n2
    LIMIT 1
</select>
```
nGQL 中，相等的判断使用  `==`，另外，关系需要有变量来接收，这里使用  `r`

**Comment by DawnZzzzz** [comment]
```
MATCH p=(n: person)-[r]->(n2: person)
        WHERE id(n) == '${name1}',id(n2) == '${name2}'
        RETURN n, r, n2
        LIMIT 1
```
 数据查询失败： 数据查询失败SyntaxError: syntax error near `r]-(n2: '

**Comment by CorvusYe** [comment]
大意了~

```diff
MATCH p=(n: person)-[r]->(n2: person)
-        WHERE id(n) == '${name1}',id(n2) == '${name2}'
+        WHERE id(n) == '${name1}' and id(n2) == '${name2}'
        RETURN n, r, n2
        LIMIT 1
```

**Comment by DawnZzzzz** [comment]
感谢叶老师！这个可以了。
```
 <insert id="insertEdge1" >
        insert edge relation(relation) values '${name1}'->'${name2}':('${relation}')
    </insert>
```
```
@PostMapping("/add/relation")
    public String addRelation(String name1,Relation relation,String name2){
        /*Person person1 = personDao.selectById(name1);
        Person person2 = personDao.selectById(name2);*/
        personDao.insertEdge1(name1,relation,name2);
        System.out.println(relation + "添加成功!");
        return "success";
    }
```
```
 void insertEdge1(@Param("name1") String name1, @Param("relation") Relation relation, @Param("name2") String name2);
```
关系显示的是这个：
[:relation@0 {relation: "{"relation":"属于"}"}

正常应该是这个：
[:relation@0 {relation: "属于"}]
不知道哪里多出来了

**Comment by CorvusYe** [comment]
这边关系直接传的是 Relation 对象。里面应该还有一个 relation 属性吧，而期望保存的是里面的属性，写法上跟期望有些不符。可以试试下面这个：
```diff
 <insert id="insertEdge1" >
-        insert edge relation(relation) values '${name1}'->'${name2}':('${relation}')
+       insert edge relation(relation) values '${name1}'->'${name2}':('${relation.relation}')
    </insert>
```

**Comment by DawnZzzzz** [comment]
感谢叶老师！

**Comment by DawnZzzzz** [comment]
好的，谢谢叶老师，最后一个问题，也是关于post请求
我已经把name设置为主键了，为什么赋值的时候name直接赋给了vid但peron.name却是空值

输出：Person(name=张三, id=edb5a677-d815-418b-bcd6-97104241148c, meta_type=人物, company=大学, post=学生, gender=on, birthday=199905, title=博士, state=正式)添加成功!
数据库中：("张三" :person{birthday: "199905", company: "大学", gender: "on", id: "edb5a677-d815-418b-bcd6-97104241148c", meta_type: "人物",  name: __NULL__, post: "学生", state: "正式", title: "博士"})

```
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "person")
public class Person {

    @Id
    private String name;
    private String id=java.util.UUID.randomUUID().toString();
    private String meta_type;
    private String company;
    private String post;
    private String gender;
    private String birthday;
    private String title;
    private String state;

}
```
``` 
@RequestMapping(value = "/add/person")
    public String person(){
        return "person_add";
    }
    @PostMapping(value = "/add/person")
    public  String addPerson(Person person){
        personDao.insert(person);
        System.out.println(person + "添加成功!");
        return "success";
    }
```
<table>
        <tr>
            <th colspan="2">add person</th>
        </tr>

        <tr>
            <td>元数据类型</td>
            <td>
                <input type="text" name="meta_type">
            </td>
        </tr>
        <tr>
            <td>姓名</td>
            <td>
                <input type="text" name="name">
            </td>
        </tr>
        <tr>
            <td>单位</td>
            <td>
                <input type="text" name="company">
            </td>
        </tr>
        <tr>
            <td>职务</td>
            <td>
                <input type="text" name="post">
            </td>
        </tr>
        <tr>
            <td>性别</td>
            <td>
                <input id="man" type="radio" checked="checked" name="gender"/>男
                <input type="radio" id="woman" name="gender">女
            </td>
        </tr>
        <tr>
            <td>生日</td>
            <td>
                <input type="text" name="birthday">
            </td>
        </tr>
        <tr>
            <td>职称</td>
            <td>
                <input type="text" name="title">
            </td>
        </tr>
        <tr>
            <td>状态</td>
            <td>
                <input type="text" name="state">
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" name="add">
            </td>
        </tr>
    </table>
```

**Comment by CorvusYe** [comment]
数据库中，主键有自己独立的栏位，为了不造成数据冗余，不再对java中标记了主键的属性进行存储。

数据库schema中这个属性也可以做相应的移除，不妨碍数据读写。

**Comment by DawnZzzzz** [comment]
嗯嗯谢谢叶老师，暂时没有问题了，我把问题关闭啦
