### ISSUE TITLE
图库点为空的时候，查询返回的结果不会为null，导致查询结果不准。

### ISSUE THREAD

**Issue by Szt-1** [nebula-contrib/ngbatis#59]
![image](https://user-images.githubusercontent.com/59354286/194990145-8bddc64c-9a8e-4f8e-b969-24f2e1eca7a6.png)
如图，结果都是空，但是api返回的结果如下：
![image](https://user-images.githubusercontent.com/59354286/194990240-ef3c3101-b7c9-4253-af3a-35c4e5c747c1.png)
size应该为0

**Comment by CorvusYe** [comment]
方便在 MapResultHandler 的 handler 方法上断点看看 result 的值不

我这边相同的 nGQL, studio 拿到的 nodes 跟 relationships 都是 []，结果是
```json
{
    "nodes": [],
    "relationships": []
}
```
![image](https://user-images.githubusercontent.com/15630211/194993556-2e7dbbac-78c1-49e4-b23d-e7c341c67ff3.png)

![image](https://user-images.githubusercontent.com/15630211/194993506-2729e7af-ac2a-4064-9241-56f9e16e2ba4.png)

**Comment by Szt-1** [comment]
![image](https://user-images.githubusercontent.com/59354286/194994141-bf14373b-d501-4df8-9026-a9bcb51e079f.png)

**Comment by Szt-1** [comment]
我看到问题了，不是api的问题，是图库返回了默认点。。。。

**Comment by CorvusYe** [comment]
好的~
如果控制台需要 nGQL 输出方便调试，可以做如下配置：
```yml
logging:
  level:
    org.nebula.contrib: DEBUG
```

**Comment by CorvusYe** [comment]
@Szt-1 
问题解决了这个issue我就关了哈 ~ 
ps: 周三有个[社区交流](https://meeting.tencent.com/dm/F8NX1aRZ8PQv)有兴趣可以来聊一聊
