### ISSUE TITLE
数据查询失败： 数据查询失败Scan vertices or edges need to specify a limit number, or limit number can not push down.

### ISSUE THREAD

**Issue by Bingai077** [nebula-contrib/ngbatis#65]
demo项目测试用例跑不通，selectByIds方法实现有问题
![image](https://user-images.githubusercontent.com/51192624/197700040-3e84bfcb-6e7d-4104-9030-258368b6d1a8.png)
执行结果：
![image](https://user-images.githubusercontent.com/51192624/197700263-4f4495ea-228f-4f82-95c0-f5c6333828c8.png)

**Comment by CorvusYe** [comment]
方便提供下NebulaGraph版本跟Schema吗

**Comment by CorvusYe** [comment]
可能是少索引了
```sql
CREATE TAG INDEX `person_idx` on `person`() 
```

**Comment by Bingai077** [comment]
是索引少了，加了索引就好了，谢谢

**Comment by wey-gu** [comment]
奇怪，请问 @Bingai077 你在用什么版本的 NebulaGraph? 可以给执行一下 

```
explain match(n:person) where id(n) IN  ["foo", "bar"] return n
```

么？这个查询按理说不需要索引的

**Comment by wey-gu** [comment]
> 是索引少了，加了索引就好了，谢谢

如果索引不是必须的，可以删掉索引更新包到最新 @CorvusYe 暂时绕过了这个 内核 bug 的触发，同时这种查询不通过索引的效率也更高一些。

**Comment by wey-gu** [comment]
嗯嗯，内核合并了修复，我测试了已经可以了哈，不过还没包含在 release 里，咱们要不先保持不用参数一阵子？

**Comment by CorvusYe** [comment]
> 嗯嗯，内核合并了修复，我测试了已经可以了哈，不过还没包含在 release 里，咱们要不先保持不用参数一阵子？

行，期待下个release
