### ISSUE TITLE
Maven 依赖包无法下载

### ISSUE THREAD

**Issue by hejiahuichengxuyuan** [nebula-contrib/ngbatis#7]
未解析的依赖项: 'org.nebula-contrib:ngbatis:jar:1.1.0-beta'

请问是我的问题吗？我不太明白，我是根据文档拷贝下来的

```xml
 <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>ossrh</id>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>
```

```xml
  <dependency>
      <groupId>org.nebula-contrib</groupId>
      <artifactId>ngbatis</artifactId>
      <version>1.1-SNAPSHOT</version>
    </dependency>
```

**Comment by wey-gu** [comment]
不是你的问题，我们上传 maven 遇到了问题，不知道为什么没能发布成功o(╥﹏╥)o

**Comment by wey-gu** [comment]
https://github.com/nebula-contrib/ngbatis/commit/3da397b0df8473dddf64c36502d35c270bd091ea#commitcomment-80776386

**Comment by wey-gu** [comment]
Now with the release/maven publican being fixed by @CorvusYe , could you retry?

**Comment by CorvusYe** [comment]
如果不行的话，可以试试改把配置改成下面的
```diff
-            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
+           <url>https://s01.oss.sonatype.org/content/repositories/releases</url>
```
第一次尝试还不确定哪个版本能用，本地环境也不好确定是哪个起作用。
如果可以的话，能不能给我个反馈，非常感谢。
@hejiahuichengxuyuan

**Comment by CorvusYe** [comment]
Docs on three topics in Chinese have been published

[By Custom nGQL](https://corvusye.github.io/ngbatis-docs/#/?path=dev-example&file=custom-crud)
[Param Usage](https://corvusye.github.io/ngbatis-docs/#/?path=dev-example&file=parameter-use)
[Result Mapping](https://corvusye.github.io/ngbatis-docs/#/?path=dev-example&file=result)

**Comment by hejiahuichengxuyuan** [comment]
@CorvusYe 首先谢谢你的回复，但是还是无法下载。

**Comment by wey-gu** [comment]
嗯嗯，我看这个网站上也能搜到(mirror)，可以么？

https://mvnrepository.com/artifact/org.nebula-contrib/ngbatis/1.1.0-beta

```xml
<!-- https://mvnrepository.com/artifact/org.nebula-contrib/ngbatis -->
<dependency>
    <groupId>org.nebula-contrib</groupId>
    <artifactId>ngbatis</artifactId>
    <version>1.1.0-beta</version>
</dependency>
```

- https://s01.oss.sonatype.org/content/repositories/releases/org/nebula-contrib/ngbatis/
- https://mvnrepository.com/artifact/org.nebula-contrib/ngbatis

**Comment by CorvusYe** [comment]
@hejiahuichengxuyuan 
你本地maven仓库应该会有一个之前没下载成功的空包，先把空包删掉再试试。

**Comment by hejiahuichengxuyuan** [comment]
```xml
-<distributionManagement>
-		<snapshotRepository>
-			<id>ossrh</id>
-			<url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
-		</snapshotRepository>
-		<repository>
-			<id>ossrh</id>
-			<url>https://s01.oss.sonatype.org/content/repositories/releases</url>
-		</repository>
-</distributionManagement>
```

- 去掉这个就可以下载了

**Comment by hejiahuichengxuyuan** [comment]
```xml
-<distributionManagement>
-		<snapshotRepository>
-			<id>ossrh</id>
-			<url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
-		</snapshotRepository>
-		<repository>
-			<id>ossrh</id>
-			<url>https://s01.oss.sonatype.org/content/repositories/releases</url>
-		</repository>
-</distributionManagement>
```

- 去掉就可以下载了

**Comment by hejiahuichengxuyuan** [comment]
<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://s01.oss.sonatype.org/content/repositories/releases</url>
		</repository>
</distributionManagement>


- 去掉就可以下载了

**Comment by hejiahuichengxuyuan** [comment]
```
<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://s01.oss.sonatype.org/content/repositories/releases</url>
		</repository>
</distributionManagement>
```

- 去掉就可以下载了
