### ISSUE TITLE
能否配置多数据源？

### ISSUE THREAD

**Issue by zb139407** [nebula-contrib/ngbatis#71]

**Comment by CorvusYe** [comment]
这里的多数据源提的是多个NebulaGraph，还是一个NebulaGraph+其他数据库？

**Comment by CorvusYe** [comment]
目前只支持一个NebulaGraph，独立在Springboot数据源之外，如果有其他非Nebula的数据库需要连接，按springboot的多数据源配置即可。

**Comment by zb139407** [comment]
多个NebulaGraph图空间

**Comment by CorvusYe** [comment]
支持的。可以参考: https://github.com/nebula-contrib/ngbatis/issues/15

**Comment by zb139407** [comment]
了解
