### ISSUE TITLE
默认的selectById()查询异常Scan vertices or edges need to specify a limit number, or limit number can not push down.

### ISSUE THREAD

**Issue by zb139407** [nebula-contrib/ngbatis#73]
- 执行默认的selectById()会报异常

![image](https://user-images.githubusercontent.com/62243886/199211931-865cce7b-7ff2-4571-9fba-ebec8adcbac1.png)
![image](https://user-images.githubusercontent.com/62243886/199215517-441a5538-6830-4507-a230-94ef863ac4e4.png)

- tag建立索引，修改xml中查询语句指定tag，可正常得出结果
`match (n:organization) where id(n) == $id return n`

- 不建立索引，xml中查询语句指定点的vid同样能查出结果
`match (n) where id(n) == '00005' return n`

请问这有更好的解决方式吗

**Comment by CorvusYe** [comment]
可能跟#65 是同样的问题。
如果指定 tag 不需要建索引的话，可以试试：
```xml
   match (n: `${ ng.tagName( ng_args[0], ng_cm ) }`) where id(n) == $id return n
```
如果测试通过，欢迎提 PR ~  
提 pr 的话，可以在 pom.xml 中追加上作者信息。

**Comment by CorvusYe** [comment]
或者
```sql
   match (n) where id(n) == ${ ng.valueFmt( id ) } return n
```

**Comment by zb139407** [comment]
不建索引，不指定tag，`match (n) where id(n) == ${ ng.valueFmt( id ) } return n`测试可行
不建索引，match (n: `${ ng.tagName( ng_args[0], ng_cm ) }`) where id(n) == $id return n测试查询异常

**Comment by zb139407** [comment]
ng.valueFmt()是哪儿的语句呀？

**Comment by CorvusYe** [comment]
那就还是跟#65 是同一个问题，没有索引不支持参数化。
PR PR～
