### ISSUE TITLE
troubleshoot the maven publican issue

### ISSUE THREAD

**Issue by wey-gu** [nebula-contrib/ngbatis#8]
- https://github.com/nebula-contrib/ngbatis/commit/3da397b0df8473dddf64c36502d35c270bd091ea#commitcomment-80776386
- https://github.com/nebula-contrib/ngbatis/actions/runs/2808799269

**Comment by wey-gu** [comment]
@CorvusYe let's talk about this here.

BTW, I received this from sonatype, could the viability be the actual cause?

https://sbom.lift.sonatype.com/report/T1-a0368c8f29fdaa555824-851247e892644d-1660204700-91bc10dde2434b289d9600b6c3f69b3e

<img width="555" alt="Screen Shot 2022-08-11 at 4 26 02 PM" src="https://user-images.githubusercontent.com/1651790/184093685-916fe6b0-7b45-487b-afff-09cade737932.png">

**Comment by wey-gu** [comment]
Or we could refer to https://github.com/nebula-contrib/nebula-jdbc/blob/master/pom.xml ?

**Comment by CorvusYe** [comment]
I saw a link in the log, which may be helpful https://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by wey-gu** [comment]
> I saw a link in the log, which may be helpful https://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

comparing to https://github.com/nebula-contrib/nebula-jdbc/blob/master/pom.xml (Yes, i know nothing about java/maven, just 0-knowledge troubleshoot), we have some more build xml-dom could we remove some of them first?

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.6.7</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>ossrh</serverId>
                    <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9.1</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.5</version>
            </plugin>
        </plugins>
    </build>
```

**Comment by wey-gu** [comment]
@CorvusYe 👍🏻 b2b11eb6a41b74cdb67a49dc074938a19e1c2bae works!

**Comment by wey-gu** [comment]
closing it 👍🏻 @CorvusYe thanks!

**Comment by CorvusYe** [comment]
https://s01.oss.sonatype.org/content/repositories/releases/org/nebula-contrib/ngbatis/
