### ISSUE TITLE
Map结果集数据类型转换器报异常

### ISSUE THREAD

**Issue by zb139407** [nebula-contrib/ngbatis#88]
![微信图片_20221116175850](https://user-images.githubusercontent.com/62243886/202149578-76f6177d-3420-42d1-87ff-d876e5b46313.png)
查询数据返回为空时，map接收会报异常
![image](https://user-images.githubusercontent.com/62243886/202150463-bfa0bc2f-583a-4950-9897-fb477f19f4ec.png)

**Comment by CorvusYe** [comment]
可以用#56 的方式先临时规避，或者clone master到本地

**Comment by zb139407** [comment]
好的
