### ISSUE TITLE
插入数据后，返回的result是null，报错Only support convert boolean/float/int/string/map/list to nebula.Value but wasjava.sql.Timestamp

### ISSUE THREAD

**Issue by btbox** [nebula-contrib/ngbatis#89]
![image](https://user-images.githubusercontent.com/43517569/202841786-b5c412a7-e37e-4f2d-bfbd-ac16da694110.png)

**Comment by hejiahuichengxuyuan** [comment]
我将valueFmt 的函数转换成自己自定义的，date是转换成string而不用datetime()

```
public class MyValueFmtFn extends AbstractFunction<Object, Boolean, Void, Void, Void, Void> {

  @Override
  public Object call(Object value, Boolean ifStringLike) {
    ifStringLike = ifStringLike != null && ifStringLike;
    if (value == null) {
      return null;
    }
    if (value instanceof String) {
      return ifStringLike ? "'.*" + value + ".*'" : "'" + value + "'";
    }

    if (value instanceof Date) {
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.sss");
//      String fn = "datetime";
//      Class<?> objClass = value.getClass();
//      fn = objClass == java.util.Date.class ? "datetime"
//        : objClass == java.sql.Date.class ? "date"
//          : objClass == java.sql.Time.class ? "time"
//            : fn;
      return String.format("'%s'", sdf.format(value));
    }
    return value;
  }
}
```

**Comment by hejiahuichengxuyuan** [comment]
我的数据是 pgsql的，字段是 timestamp 我看见他转换成参数变为时间戳了
![image](https://user-images.githubusercontent.com/43517569/202842211-9944d590-6be8-44f7-8ead-b03440294653.png)

**Comment by CorvusYe** [comment]
使用ng_args可以拿到最原始的数据类型

**Comment by CorvusYe** [comment]
> ![image](https://user-images.githubusercontent.com/43517569/202841786-b5c412a7-e37e-4f2d-bfbd-ac16da694110.png)
> 

还有一种方式，可以在DefaultArgsResolver追加Timestamp类型的value setter

**Comment by CorvusYe** [comment]
> 我将valueFmt 的函数转换成自己自定义的，date是转换成string而不用datetime()
> 
> ```
> public class MyValueFmtFn extends AbstractFunction<Object, Boolean, Void, Void, Void, Void> {
> 
>   @Override
>   public Object call(Object value, Boolean ifStringLike) {
>     ifStringLike = ifStringLike != null && ifStringLike;
>     if (value == null) {
>       return null;
>     }
>     if (value instanceof String) {
>       return ifStringLike ? "'.*" + value + ".*'" : "'" + value + "'";
>     }
> 
>     if (value instanceof Date) {
>       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.sss");
> //      String fn = "datetime";
> //      Class<?> objClass = value.getClass();
> //      fn = objClass == java.util.Date.class ? "datetime"
> //        : objClass == java.sql.Date.class ? "date"
> //          : objClass == java.sql.Time.class ? "time"
> //            : fn;
>       return String.format("'%s'", sdf.format(value));
>     }
>     return value;
>   }
> }
> ```


这个是你的解决方案吗

刚刚跟了一下代码，感觉自己的回复理解错了。
是调用的 基类的 insert 接口插入的还是自己写的 xml

**Comment by hejiahuichengxuyuan** [comment]
并不是的，我又发现 数据查询失败：Only support convert boolean/float/int/string/map/list to nebula.Value but wasjava.math.BigDecimal
应该是参数转换问题？

**Comment by CorvusYe** [comment]
有个新版本正在发布中，这个类型的问题一会儿一并修复哈～

**Comment by hejiahuichengxuyuan** [comment]
好的谢谢，

**Comment by hejiahuichengxuyuan** [comment]
我在更新1.1.0后，发生报错：数据查询失败：Only support convert boolean/float/int/string/map/list to nebula.Value but wasjava.util.HashSet，但是我用的是自己拼接的字符串，插入的字段和value都是我字符串拼接的
插入日志如下
```
INSERT VERTEX tag_milk
        (
        `price`,
        `brand`,
        `key`
        )
        VALUES
        "milk_yili_2":(49.9,"\u4F0A\u5229","yili_2");
	- params: {spaceName=subgraph_1669728312405, tagName=tag_milk, params=["price","brand","key"], dataStr="milk_yili_2":(49.9,"\u4F0A\u5229","yili_2")}
	- result：null
```

**Comment by CorvusYe** [comment]
1.1.0 没发布成功呀，可以在配置 ngbatis 的地方写把这段加进去，替换掉原有的 value setter
```java
COMPLEX_TYPE_AND_SETTER.put(
    Set.class, 
    (Setter<Set<?>>) (set) -> {
      List<Object> values = new ArrayList<>();
      set.forEach(el -> values.add(toNebulaValueType(el)));
      return values;
    });
```

**Comment by CorvusYe** [comment]
> 我在更新1.1.0后，发生报错：数据查询失败：Only support convert boolean/float/int/string/map/list to nebula.Value but wasjava.util.HashSet，但是我用的是自己拼接的字符串，插入的字段和value都是我字符串拼接的 插入日志如下
> 
> ```
> INSERT VERTEX tag_milk
>         (
>         `price`,
>         `brand`,
>         `key`
>         )
>         VALUES
>         "milk_yili_2":(49.9,"\u4F0A\u5229","yili_2");
> 	- params: {spaceName=subgraph_1669728312405, tagName=tag_milk, params=["price","brand","key"], dataStr="milk_yili_2":(49.9,"\u4F0A\u5229","yili_2")}
> 	- result：null
> ```

因为ngbatis并没有对xml内的内容进行解析，不能确定哪些区分哪些参数是自己拼接哪些参数是给nebula占位符的
所以目前传给 dao 的参数都会再传给 nebula。
原来的序列化有一些问题。

**Comment by CorvusYe** [comment]
> 我在更新1.1.0后，发生报错：数据查询失败：Only support convert boolean/float/int/string/map/list to nebula.Value but wasjava.util.HashSet，但是我用的是自己拼接的字符串，插入的字段和value都是我字符串拼接的 插入日志如下
> 
> ```
> INSERT VERTEX tag_milk
>         (
>         `price`,
>         `brand`,
>         `key`
>         )
>         VALUES
>         "milk_yili_2":(49.9,"\u4F0A\u5229","yili_2");
> 	- params: {spaceName=subgraph_1669728312405, tagName=tag_milk, params=["price","brand","key"], dataStr="milk_yili_2":(49.9,"\u4F0A\u5229","yili_2")}
> 	- result：null
> ```

因为ngbatis并没有对xml内的内容进行解析，不能确定哪些区分哪些参数是自己拼接哪些参数是给nebula占位符的
所以目前传给 dao 的参数都会再传给 nebula。
原来的序列化有一些问题。

**Comment by hejiahuichengxuyuan** [comment]
明白，谢谢大佬
