### ISSUE TITLE
循环多次调用插入方法后报StackOverflow Error

### ISSUE THREAD

**Issue by zhzhseu** [nebula-contrib/ngbatis#90]
出错信息和代码位置：
![image](https://user-images.githubusercontent.com/23006795/203196003-a13cf87b-e4de-417e-a5cc-d9d858675019.jpeg)

xml插入语句：
![image](https://user-images.githubusercontent.com/23006795/203196124-0b95ebb0-db16-4163-8cee-9fca80b03513.jpeg)

测试代码：
![image](https://user-images.githubusercontent.com/23006795/203196190-7efee78e-73eb-46ae-be94-3f2c73f72aab.jpeg)

循环次数超过200次后就会报StackOverflowError，后续换了一种batch的插入方式后，就没有问题。
这个错误是使用不正确还是bug？

**Comment by CorvusYe** [comment]
应该算不好定位的bug... 量大的时候我自己一般会2000条批量，5000的话，可能会报错，nebula一次能接受的字节数有限

**Comment by CorvusYe** [comment]
可以参考#63 修改JVM的Xss来解决

**Comment by zhzhseu** [comment]
> 可以参考#63 修改JVM的Xss来解决

调大Xss后问题解决，感谢！
