### ISSUE TITLE
xml中的$p0为什么获取不到

### ISSUE THREAD

**Issue by keyouth0** [nebula-contrib/ngbatis#93]
我参照了提供的示例进行测试，开始传递一个字符串时一直查不到数据，于是又尝试传递一个Person对象，这个时候出现报错，提示变量不存在。
![image](https://user-images.githubusercontent.com/56377951/204243412-71f2cbe8-5961-40f4-bb5b-c25b6fcee0a5.png)

![image](https://user-images.githubusercontent.com/56377951/204243175-23af4ca3-8a29-461a-93e3-f7c2899e8d48.png)

![image](https://user-images.githubusercontent.com/56377951/204243293-c2e75a99-7fa3-45b5-b8ed-978475425b1e.png)

**Comment by CorvusYe** [comment]
传递一个POJO对象的时候直接用里面的属性就可以了，比如说 `$name` 或者 `${name}`

**Comment by CorvusYe** [comment]
这边如果参数很明确，`personDao.selectByName(name);` 这样的方式，使用 `$p0` 就很合适

**Comment by keyouth0** [comment]
> 传递一个POJO对象的时候直接用里面的属性就可以了，比如说 `$name` 或者 `${name}`

尝试了一下可以了，再次重新尝试`$p0`也没有问题，不知道昨天是什么情况，`$p0`一直查不到数据。感谢！

**Comment by CorvusYe** [comment]
可以就行，对象类型跟基本类型（含String）xml中参数名会有所不同。

**Comment by keyouth0** [comment]
> 传递一个POJO对象的时候直接用里面的属性就可以了，比如说 `$name` 或者 `${name}`

尝试了一下可以了，再次重新尝试`$p0`也没有问题，不知道昨天是什么情况，`$p0`一直查不到数据。感谢！
